### ISSUE TITLE
[bug] qtAliceVision plugin crashes on HDR button

### ISSUE THREAD

**Issue by skinkie** [alicevision/meshroom#1116]
**Describe the bug**
When pressing HDR on any photo I end up with this crash:

```
(gdb) bt
#0  0x00007ffff7e093a1 in raise () at /lib64/libc.so.6
#1  0x00007ffff7df2546 in abort () at /lib64/libc.so.6
#2  0x00007ffff7e4c107 in __libc_message () at /lib64/libc.so.6
#3  0x00007ffff7e53f7a in  () at /lib64/libc.so.6
#4  0x00007ffff7e55780 in _int_free () at /lib64/libc.so.6
#5  0x00007fff66fb0a2a in Eigen::internal::aligned_free(void*) (ptr=0x7ffef02de020) at /usr/include/eigen3/Eigen/src/Core/util/Memory.h:177
#6  0x00007fff66fb9523 in Eigen::internal::conditional_aligned_free<true>(void*) (ptr=0x7ffef02de020) at /usr/include/eigen3/Eigen/src/Core/util/Memory.h:230
#7  0x00007fff66fbfc6b in Eigen::internal::conditional_aligned_delete_auto<aliceVision::image::Rgba<float>, true>(aliceVision::image::Rgba<float>*, unsigned long) (ptr=0x7ffef02de020, size=8294400)
    at /usr/include/eigen3/Eigen/src/Core/util/Memory.h:416
#8  0x00007fff66fbde17 in Eigen::DenseStorage<aliceVision::image::Rgba<float>, -1, -1, -1, 1>::~DenseStorage() (this=0x7fff5d7dccc8, __in_chrg=<optimized out>) at /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:391
#9  0x00007fff66fba286 in Eigen::PlainObjectBase<Eigen::Matrix<aliceVision::image::Rgba<float>, -1, -1, 1, -1, -1> >::~PlainObjectBase() (this=0x7fff5d7dccc8, __in_chrg=<optimized out>)
    at /usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:98
#10 0x00007fff66fba2a2 in Eigen::Matrix<aliceVision::image::Rgba<float>, -1, -1, 1, -1, -1>::~Matrix() (this=0x7fff5d7dccc8, __in_chrg=<optimized out>) at /usr/include/eigen3/Eigen/src/Core/Matrix.h:178
#11 0x00007fff66fba2d4 in aliceVision::image::Image<aliceVision::image::Rgba<float> >::~Image() (this=0x7fff5d7dccc0, __in_chrg=<optimized out>) at /opt/alicevision/include/aliceVision/image/Image.hpp:95
#12 0x00007fff66fe603c in qtAliceVision::FloatImageIORunnable::run() (this=0x3657820) at /home/skinkie/Sources/meshroom/qtAliceVision/src/FloatImageViewer.cpp:100
#13 0x00007ffff5edc905 in  () at /usr/lib64/libQt5Core.so.5
#14 0x00007ffff5edb392 in  () at /usr/lib64/libQt5Core.so.5
#15 0x00007ffff7a42fee in start_thread () at /lib64/libpthread.so.0
#16 0x00007ffff7ecdd7f in clone () at /lib64/libc.so.6
```

**Comment by natowi** [comment]
Does this persist in version 2021?
