### ISSUE TITLE
Error when Quitting the application

### ISSUE THREAD

**Issue by gnatty7** [alicevision/meshroom#115]
Windows 10
Python 2.7.15 32-bit
Qt 5.10.1
PySide2 5.9

Meshroom develop - f7da048addcf24f73ae23a3e35a8510a82df9d45

```
Traceback (most recent call last):
  File "D:\Work\apps\meshroom\venv\lib\site-packages\meshroom\ui\reconstruction.py", line 428, in _setSfm
    self.updateViewsAndPoses()
  File "D:\Work\apps\meshroom\venv\lib\site-packages\meshroom\ui\reconstruction.py", line 413, in updateViewsAndPoses
    self._views, self._poses = self._sfm.nodeDesc.getViewsAndPoses(self._sfm)
AttributeError: 'PySide2.QtCore.QObject' object has no attribute 'nodeDesc'
```

**Comment by fabiencastan** [comment]
Fixed by #116.
