### ISSUE TITLE
Using meshroom with Colab - how do I properly edit and run the .mg file in colab?

### ISSUE THREAD

**Issue by RayzedByRobots** [alicevision/meshroom#1205]
Hi - I am trying to use my own .mg meshroom file in google colab and I have hit a couple snags. The only two changes from the default .mg in meshroom is using high for featureExtraction and using guided matching.

I used the how to from here: https://github.com/alicevision/meshroom/issues/851

My PC meshroom version is 2020.1.1 
The meshroom version being used in the colab notebook from github is 2019.1.0 

The changes I made to the .mg file: 
My input images are in google drive, E2 folder, so I edited the path in my .mg file: 
"sensorDatabase": "/content/drive/MyDrive/Science/Coral/PDAM_H_Davis/E2",

The other change is below which now points to the .tree file in google drive
"tree": "/content/meshroom/Meshroom-2019.1.0/aliceVision/share/aliceVision/vlfeat_K80L3.SIFT.tree",

As the link above describes, under "Meshing" I inputted the following which points to my edited .mg file
!./meshroom/Meshroom-2019.1.0/meshroom_compute --forceCompute /content/drive/MyDrive/Science/MeshroomRunFiles/MyMESHwHigh.mg 

And then I get the following error(s) - as you can see something is not right with finding the images and then maybe a version conflict? I've been at this for about 3 weeks, any help would be appreciated! I think I'm close. 

mkdir: cannot create directory ‘/content/drive/MyDrive/Science/Coral/PDAM_H_Davis/E2’: File exists
Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
WARNING:root:Compatibility issue detected for node 'CameraInit_1': VersionConflict
WARNING:root:Compatibility issue detected for node 'FeatureExtraction_1': DescriptionConflict
WARNING:root:Compatibility issue detected for node 'ImageMatching_1': VersionConflict
WARNING:root:Compatibility issue detected for node 'FeatureMatching_1': DescriptionConflict
WARNING:root:Compatibility issue detected for node 'StructureFromMotion_1': DescriptionConflict
WARNING:root:Compatibility issue detected for node 'PrepareDenseScene_1': VersionConflict
WARNING:root:Compatibility issue detected for node 'DepthMapFilter_1': VersionConflict
WARNING:root:Compatibility issue detected for node 'Meshing_1': VersionConflict
WARNING:root:Compatibility issue detected for node 'MeshFiltering_1': VersionConflict
WARNING:root:Compatibility issue detected for node 'Texturing_1': VersionConflict
Nodes to execute:  ['CameraInit_1', 'FeatureExtraction_1', 'ImageMatching_1', 'FeatureMatching_1', 'StructureFromMotion_1', 'PrepareDenseScene_1', 'DepthMap_1', 'DepthMapFilter_1', 'Meshing_1', 'MeshFiltering_1', 'Texturing_1']
WARNING: downgrade status on node "CameraInit_1" from Status.ERROR to Status.SUBMITTED

[1/11] CameraInit
 - commandLine: aliceVision_cameraInit  --sensorDatabase "/content/drive/MyDrive/Science/Coral/PDAM_H_Davis/E2" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "/content/drive/MyDrive/Science/MeshroomRunFiles/MeshroomCache/CameraInit/ac38bdd16b58bc6daeecdeacbfc7df059355110f/cameraInit.sfm" --allowSingleView 1 
 - logFile: /content/drive/MyDrive/Science/MeshroomRunFiles/MeshroomCache/CameraInit/ac38bdd16b58bc6daeecdeacbfc7df059355110f/log
 - elapsed time: 0:00:00.272960
ERROR:root:Error on node computation: Error on node "CameraInit_1":
Log:
Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "20EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "" (default)
 * output = "/content/drive/MyDrive/Science/MeshroomRunFiles/MeshroomCache/CameraInit/ac38bdd16b58bc6daeecdeacbfc7df059355110f/cameraInit.sfm"
 * sensorDatabase = "/content/drive/MyDrive/Science/Coral/PDAM_H_Davis/E2"
 * verboseLevel = "info"

[17:08:10.119586][error] Program need -i or --imageFolder option
No input images.

WARNING: downgrade status on node "ImageMatching_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "StructureFromMotion_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/opt/Meshroom/setupInitScriptUnix.py", line 39, in run
  File "bin/meshroom_compute", line 64, in <module>
  File "/opt/Meshroom/meshroom/core/graph.py", line 1131, in executeGraph
  File "/opt/Meshroom/meshroom/core/node.py", line 271, in process
  File "/opt/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 239, in processChunk
  File "/opt/Meshroom/meshroom/core/desc.py", line 452, in processChunk
RuntimeError: Error on node "CameraInit_1":
Log:
Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "20EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "" (default)
 * output = "/content/drive/MyDrive/Science/MeshroomRunFiles/MeshroomCache/CameraInit/ac38bdd16b58bc6daeecdeacbfc7df059355110f/cameraInit.sfm"
 * sensorDatabase = "/content/drive/MyDrive/Science/Coral/PDAM_H_Davis/E2"
 * verboseLevel = "info"

[17:08:10.119586][error] Program need -i or --imageFolder option
No input images.

**Comment by RayzedByRobots** [comment]
I have now matched my meshroom versions. I have downloaded meshroom version 2019.1.0 to my PC and created a .mg file that uses High FeatureExtraction and Guided Matching. Colab also is using 2019.1.0. However when I run - Meshroom can't find the input images. I will open a new issue. 


Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
Nodes to execute:  ['CameraInit_1', 'FeatureExtraction_1', 'ImageMatching_1', 'FeatureMatching_1', 'StructureFromMotion_1', 'PrepareDenseScene_1', 'DepthMap_1', 'DepthMapFilter_1', 'Meshing_1', 'MeshFiltering_1', 'Texturing_1']
WARNING: downgrade status on node "CameraInit_1" from Status.ERROR to Status.SUBMITTED

[1/11] CameraInit
 - commandLine: aliceVision_cameraInit  --sensorDatabase "/content/drive/MyDrive/Science/Coral/PDAM_H_Davis/E2_Folder" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "/content/drive/MyDrive/Science/MeshroomRunFiles/MeshroomCache/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm" --allowSingleView 1 
 - logFile: /content/drive/MyDrive/Science/MeshroomRunFiles/MeshroomCache/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/log
 - elapsed time: 0:00:00.185615
ERROR:root:Error on node computation: Error on node "CameraInit_1":
Log:
Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "20EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "" (default)
 * output = "/content/drive/MyDrive/Science/MeshroomRunFiles/MeshroomCache/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm"
 * sensorDatabase = "/content/drive/MyDrive/Science/Coral/PDAM_H_Davis/E2_Folder"
 * verboseLevel = "info"

[12:50:03.944917][error] Program need -i or --imageFolder option
No input images.

WARNING: downgrade status on node "ImageMatching_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "StructureFromMotion_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/opt/Meshroom/setupInitScriptUnix.py", line 39, in run
  File "bin/meshroom_compute", line 64, in <module>
  File "/opt/Meshroom/meshroom/core/graph.py", line 1131, in executeGraph
  File "/opt/Meshroom/meshroom/core/node.py", line 271, in process
  File "/opt/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 239, in processChunk
  File "/opt/Meshroom/meshroom/core/desc.py", line 452, in processChunk
RuntimeError: Error on node "CameraInit_1":
Log:
Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "20EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "" (default)
 * output = "/content/drive/MyDrive/Science/MeshroomRunFiles/MeshroomCache/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm"
 * sensorDatabase = "/content/drive/MyDrive/Science/Coral/PDAM_H_Davis/E2_Folder"
 * verboseLevel = "info"

[12:50:03.944917][error] Program need -i or --imageFolder option
No input images.
