### ISSUE TITLE
Meshroom-2021.1.0 wont start on windows 10

### ISSUE THREAD

**Issue by lucianojamimbo** [alicevision/meshroom#1313]
Downloaded 2021.1.0 from the website and when i attempt to run the program i get this error

`PySide2/__init__.py: Unable to import shiboken2 from C:\Users\Administrator\Desktop\Meshroom-2021.1.0, C:\Users\Administrator\Desktop\Meshroom-2021.1.0\lib\library.zip, C:\Users\Administrator\Desktop\Meshroom-2021.1.0\lib
Traceback (most recent call last):
  File "d:\release\BUILD\meshroom\venv\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "d:\release\BUILD\meshroom\venv\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
  File "meshroom/ui/__main__.py", line 10, in <module>
  File "d:\release\BUILD\meshroom\meshroom\ui\app.py", line 5, in <module>
  File "d:\release\BUILD\meshroom\venv\lib\site-packages\PySide2\__init__.py", line 61, in <module>
  File "d:\release\BUILD\meshroom\venv\lib\site-packages\PySide2\__init__.py", line 25, in _setupQtDirectories
ModuleNotFoundError: No module named 'shiboken2'`

Meshroom-2019.2.0 appears to be running fine for me

**Comment by kugiyasan** [comment]
Look at the last line
`ModuleNotFoundError: No module named 'shiboken2'`
Try installing it with `py -m pip install shiboken2` (If you have multiple versions of python, make sure that py calls the right version with `py -V`)
Also you said that that you downloaded Meshroom from "the website", just making sure, from [the releases tab of this repo](https://github.com/alicevision/meshroom/releases/tag/v2021.1.0), right? I tried doing the same, and I didn't get the error and there isn't a meshroom/ui/ folder in my installation folder unlike your error message.

**Comment by lucianojamimbo** [comment]
I originally downloaded from https://alicevision.org/#meshroom

The version from https://github.com/alicevision/meshroom/releases/tag/v2021.1.0 works fine for me, thanks.

**Comment by kugiyasan** [comment]
Glad it worked out!!
I recommend you to close the issue, now that it is solved.
