### ISSUE TITLE
Help with error: UnboundLocalError: local variable 'allReady' referenced before assignment

### ISSUE THREAD

**Issue by bonsak** [alicevision/meshroom#1340]
**Describe the problem**
I'm trying to make a small Deadline plugin for meshroom_batch.exe. Im using the mini6 files for testing. Im trying to make the plugin be able to use a general pipeline file for rendering (See attachment: [Render.zip](https://github.com/alicevision/meshroom/files/6150420/Render.zip)
For basic testing I'm just trying to make this work from the command line in windows. I've tried with a pipeline file where the images are already imported and one with no images imported. 
I've added a Publish node at the end of the graph. I seem to get the "UnboundLocalError" regardless of which file i use. 

These are the arguments I pass to meshroom_batch.exe:
```meshroom_batch.exe 
--forceCompute 
--forceStatus 
-I "F:\Alicevision\dataset_monstree-master\mini6" 
--pipeline "F:\Alicevision\dataset_monstree-master\mini6\Render.mg" 
--output "F:\Alicevision\dataset_monstree-master\mini6\out" 
--cache "F:\Alicevision\dataset_monstree-master\mini6\cache"
```

I cant figure out if I'm doing something wrong here or if this is a bug. It seems meshroom_batch finishes the job regardless for this error. But it would be great to know why this is happening.
Any help appreciated.

Regards
Bonsak

**Dataset**
dataset_monstree-master\mini6

**Log**
```
C:\Meshroom-2021.1.0>meshroom_batch.exe --forceCompute --forceStatus -I "F:\Alicevision\dataset_monstree-master\mini6" --pipeline "F:\Alicevision\dataset_monstree-master\mini6\Render.mg" --output "F:\Alicevision\dataset_monstree-master\mini6\out" --cache "F:\Alicevision\dataset_monstree-master\mini6\cache"
Program called with the following parameters:
 * allowSingleView = 1
 * allowedCameraModels = "pinhole,radial1,radial3,brown,fisheye4,fisheye1"
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:\Users\bonsa\AppData\Local\Temp\tmph_c5yd1s/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"
 * output = "C:/Users/bonsa/AppData/Local/Temp/tmph_c5yd1s/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm"
 * sensorDatabase = "C:\Meshroom-2021.1.0\aliceVision\share\aliceVision\cameraSensors.db"
 * useInternalWhiteBalance = 1
 * verboseLevel = "info"
 * viewIdMethod =  Unknown Type "enum aliceVision::sfmDataIO::EViewIdMethod"
 * viewIdRegex = ".*?(\d+)" (default)

[16:38:23.056407][warning] Some image(s) have no serial number to identify the camera/lens device.
This makes it impossible to correctly group the images by device if you have used multiple identical (same model) camera devices.
The reconstruction will assume that only one device has been used, so if 2 images share the same focal length approximation they will share the same internal camera parameters.
6 image(s) are concerned.
[16:38:23.067395][info] CameraInit report:
        - # views listed: 6
           - # views with an initialized intrinsic listed: 6
           - # views without metadata (with a default intrinsic): 0
        - # intrinsics listed: 1
Traceback (most recent call last):
  File "d:\release\BUILD\meshroom\venv\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "d:\release\BUILD\meshroom\venv\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
  File "bin/meshroom_batch", line 206, in <module>
  File "d:\release\BUILD\meshroom\meshroom\core\taskManager.py", line 234, in compute
UnboundLocalError: local variable 'allReady' referenced before assignment
```

**Desktop (please complete the following and other pertinent information):**
 - OS: Windows
 - Python version: 3.6.4
 - Meshroom version: Meshroom-2021.1.0 (binary)

**Comment by ChemicalXandco** [comment]
Do you need the `--forceCompute` argument? It should work fine without it.

**Comment by bonsak** [comment]
Hey. Thanks a lot!
