### ISSUE TITLE
can't import images 

### ISSUE THREAD

**Issue by PPPHUB** [alicevision/meshroom#1482]
I already build the alicevision by following the [https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md](url), I use vcpgk to install all package and use visual studio 2019 to Compile. and add the release folder to path. but when I import the image it always failed and the terminal show that:

```
WARNING:root:Missing plugin qtAliceVision.
WARNING:root:Missing plugin qtOIIO.
WARNING:root:importFilesDialog fileUrls: file:///D:/monstre/full/IMG_1024.JPG
ERROR:root:Error while building intrinsics: CameraInit failed with error code 3221225595.
Command was: "aliceVision_cameraInit  --sensorDatabase "C:\Program Files\aliceVision\src\aliceVision\sensorDB\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1,3deanamorphic4,3deradial4,3declassicld --useInternalWhiteBalance True --viewIdMethod metadata --verboseLevel info --output "C:/Users/wsh22/AppData/Local/Temp/tmpfm32fhxp/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm" --allowSingleView 1 --input "C:\Users\wsh22\AppData\Local\Temp\tmpfm32fhxp/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"".

Traceback (most recent call last):
  File "D:\meshroom\meshroom\ui\reconstruction.py", line 824, in importImagesUrls
    self.importImagesFromFolder(paths)
  File "D:\meshroom\meshroom\ui\reconstruction.py", line 811, in importImagesFromFolder
    self.buildIntrinsics(self.cameraInit, filesByType.images)
  File "D:\meshroom\meshroom\ui\reconstruction.py", line 880, in buildIntrinsics
    views, intrinsics = cameraInitCopy.nodeDesc.buildIntrinsics(cameraInitCopy, additionalViews)
  File "D:\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 288, in buildIntrinsics
    raise RuntimeError('CameraInit failed with error code {}.\nCommand was: "{}".\n'.format(
RuntimeError: CameraInit failed with error code 3221225595.
Command was: "aliceVision_cameraInit  --sensorDatabase "C:\Program Files\aliceVision\src\aliceVision\sensorDB\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1,3deanamorphic4,3deradial4,3declassicld --useInternalWhiteBalance True --viewIdMethod metadata --verboseLevel info --output "C:/Users/wsh22/AppData/Local/Temp/tmpfm32fhxp/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm" --allowSingleView 1 --input "C:\Users\wsh22\AppData\Local\Temp\tmpfm32fhxp/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"".

WARNING:root:Model size of -242 is less than 0
WARNING:root:Model size of -27 is less than 0
```
Where is the problem and what should I do ?

**Comment by PPPHUB** [comment]
fixed by repairing the vc++ 2015
