### ISSUE TITLE
[question] There is no node able to be processed.

### ISSUE THREAD

**Issue by EasonC13** [alicevision/meshroom#1542]
**Describe the problem**
Originally I use  the following command and it can work.

```
./meshroom_batch --input ../input_img --output output_obj
```

Now, I want my meshroom_batch use GPU to compute feature extraction to get better performance.
I following this answer:
https://github.com/alicevision/meshroom/issues/502#issuecomment-807130647

However, when I use

```
./meshroom_batch --input ../input_img --output output_obj --paramOverrides FeatureExtraction:forceCpuExtraction=0
```

It shows the following error:

**Log**
```
[04:09:22.551590][warning] Image 'frame84.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[04:09:22.551746][warning] Image 'frame54.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[04:09:22.551899][warning] Image 'frame220.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[04:09:22.552032][warning] Some image(s) have no serial number to identify the camera/lens device.
This makes it impossible to correctly group the images by device if you have used multiple identical (same model) camera devices.
The reconstruction will assume that only one device has been used, so if 2 images share the same focal length approximationthey will share the same internal camera parameters.
333 image(s) are concerned.
[04:09:22.575845][info] CameraInit report:
        - # views listed: 333
           - # views with an initialized intrinsic listed: 333
           - # views without metadata (with a default intrinsic): 333
        - # intrinsics listed: 1


Overrides FeatureExtraction.forceCpuExtraction=0


Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/opt/Meshroom/setupInitScriptUnix.py", line 39, in run
  File "bin/meshroom_batch", line 206, in <module>
  File "/opt/Meshroom/meshroom/core/taskManager.py", line 192, in compute
  File "/opt/Meshroom/meshroom/core/taskManager.py", line 368, in raiseImpossibleProcess
RuntimeError: [COMPUTATION] Impossible Process:
There is no node able to be processed.
```

**Desktop (please complete the following and other pertinent information):**
 - OS: CentOS in docker
   - Binary version 2021.1

Want to know how to do feature extraction via command line in Mushroom

**Comment by salmanmaq** [comment]
Hi. It's been a while but were you able to make any progress with this?

**Comment by cbentejac** [comment]
This issue generally occurs when the nodes have already been computed. Here, you were trying to recompute the same scene and the `forceCpuExtraction` parameter wasn't changing the UID: https://github.com/alicevision/Meshroom/blob/ad9f1e874af5a6da47d5bb947b018b509925ddf5/meshroom/nodes/aliceVision/FeatureExtraction.py#L121 so the statuses of the nodes were never cleared.

If you were to retry this with Meshroom 2025.1.0, you wouldn't run into this issue because this parameter now triggers a UID change when its value is updated. 

More generally, you can use the `--forceCompute` option in `meshroom_batch` to compute the nodes even if their computation results already exist in the cache.
