### ISSUE TITLE
Import error with python 3.10

### ISSUE THREAD

**Issue by dpellegr** [alicevision/meshroom#1588]
Hi, I am trying to run Meshroom with python 3.10, but it fails to launch with this error:

```
File "/tmp/makepkg/meshroom/src/meshroom/meshroom/ui/reconstruction.py", line 6, in <module>
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/Meshroom-2021.1.0/lib/collections/__init__.pyc)

```
Potentially solved by this: https://programmerah.com/solved-python3-10-error-cannot-import-name-iterable-from-collections-46165/

**Comment by alfredopalhares** [comment]
I too am having this problem running meshroom on ArchLinux:
```
Meshroom
WARNING:root:== The following "submitters" plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/cx_Freeze/initscripts/__startup__.py", line 104, in run
    module_init.run(name + "__main__")
  File "/home/masterkorp/.cache/yay/meshroom/src/meshroom/setupInitScriptUnix.py", line 42, in run
  File "meshroom/ui/__main__.py", line 10, in <module>
  File "/home/masterkorp/.cache/yay/meshroom/src/meshroom/meshroom/ui/app.py", line 19, in <module>
  File "shibokensupport/__feature__.py", line 142, in _import
  File "/home/masterkorp/.cache/yay/meshroom/src/meshroom/meshroom/ui/reconstruction.py", line 6, in <module>
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/Meshroom-2021.1.0/lib/collections/__init__.pyc)
```

**Comment by alfredopalhares** [comment]
Do not stale it, has this been tested ?
