### ISSUE TITLE
Trying out meshroom with google collab for rendering. Sucessfully implemented the images available on github 

### ISSUE THREAD

**Issue by aceIsHere** [alicevision/meshroom#1636]
Program called with the following parameters:
 * allowSingleView = 1
 * allowedCameraModels = "pinhole,radial1,radial3,brown,fisheye4,fisheye1"
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "20EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "/tmp/tmpaj79ei6q/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"
 * output = "/tmp/tmpaj79ei6q/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm"
 * sensorDatabase = "/content/meshroom/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/aliceVision/share/aliceVision/cameraSensors.db"
 * useInternalWhiteBalance = 1
 * verboseLevel = "info"
 * viewIdMethod =  Unknown Type "N11aliceVision9sfmDataIO13EViewIdMethodE"
 * viewIdRegex = ".*?(\d+)" (default)

[18:07:45.539825][warning] Image '60.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.540311][warning] Image '42.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.540486][warning] Image '46.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.540686][warning] Image '51.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.540856][warning] Image '41.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.541029][warning] Image '72.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.541236][warning] Image '101.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.541456][warning] Image '36.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.541629][warning] Image '77.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.541794][warning] Image '50.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.541955][warning] Image '54.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.542125][warning] Image '35.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.542202][warning] Image '79.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.542375][warning] Image '80.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.542618][warning] Image '37.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.542823][warning] Image '86.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.542988][warning] Image '68.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.543157][warning] Image '85.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.543381][warning] Image '59.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.543572][warning] Image '99.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.543734][warning] Image '73.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.543893][warning] Image '33.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.544140][warning] Image '32.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.544347][warning] Image '93.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.544666][warning] Image '71.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.544841][warning] Image '39.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.545022][warning] Image '70.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.545205][warning] Image '34.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.545378][warning] Image '63.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.545544][warning] Image '53.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.545707][warning] Image '90.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.545884][warning] Image '83.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.546064][warning] Image '48.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.546241][warning] Image '56.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.546417][warning] Image '62.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.546582][warning] Image '43.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.546760][warning] Image '100.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.544480][warning] Image '97.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.546936][warning] Image '74.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.547117][warning] Image '78.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.547286][warning] Image '49.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.547458][warning] Image '52.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.547617][warning] Image '65.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.547784][warning] Image '82.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.547946][warning] Image '40.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.548144][warning] Image '94.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.548338][warning] Image '69.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.548504][warning] Image '96.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.548689][warning] Image '45.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.548865][warning] Image '38.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.549052][warning] Image '47.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.549415][warning] Image '64.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.549587][warning] Image '95.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.549762][warning] Image '55.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.549932][warning] Image '87.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.550111][warning] Image '61.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.550295][warning] Image '92.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.550471][warning] Image '44.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.550642][warning] Image '58.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.550815][warning] Image '75.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.550989][warning] Image '102.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.549244][warning] Image '81.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.551707][warning] Image '91.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.551830][warning] Image '84.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.551946][warning] Image '57.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.552063][warning] Image '89.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.552192][warning] Image '67.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.552308][warning] Image '88.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.552423][warning] Image '66.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.552541][warning] Image '76.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.552655][warning] Image '98.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[18:07:45.552738][warning] Some image(s) have no serial number to identify the camera/lens device.
This makes it impossible to correctly group the images by device if you have used multiple identical (same model) camera devices.
The reconstruction will assume that only one device has been used, so if 2 images share the same focal length approximation they will share the same internal camera parameters.
71 image(s) are concerned.
[18:07:45.556514][info] CameraInit report:
	- # views listed: 71
	   - # views with an initialized intrinsic listed: 71
	   - # views without metadata (with a default intrinsic): 71
	- # intrinsics listed: 1
 - commandLine: aliceVision_cameraInit  --sensorDatabase "/content/meshroom/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/aliceVision/share/aliceVision/cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1 --useInternalWhiteBalance True --viewIdMethod metadata --verboseLevel info --output "/tmp/MeshroomCache/CameraInit/9ba9a425b25abe37f064d43b71d38b831d58adf9/cameraInit.sfm" --allowSingleView 1 --input "/tmp/MeshroomCache/CameraInit/9ba9a425b25abe37f064d43b71d38b831d58adf9//viewpoints.sfm"
 - logFile: /tmp/MeshroomCache/CameraInit/9ba9a425b25abe37f064d43b71d38b831d58adf9/log
 - commandLine: aliceVision_featureExtraction  --input "/tmp/MeshroomCache/CameraInit/9ba9a425b25abe37f064d43b71d38b831d58adf9/cameraInit.sfm" --describerTypes sift --describerPreset normal --describerQuality normal --contrastFiltering GridSort --gridFiltering True --forceCpuExtraction True --maxThreads 0 --verboseLevel info --output "/tmp/MeshroomCache/FeatureExtraction/9d9e792397fc127695d5d77792a395654d8e311e" --rangeStart 0 --rangeSize 40
 - logFile: /tmp/MeshroomCache/FeatureExtraction/9d9e792397fc127695d5d77792a395654d8e311e/0.log
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 1294, in _shutdown
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 1056, in join
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
KeyboardInterrupt

**Comment by aceIsHere** [comment]
I have taken up the latest release of meshroom as well add the sensor info of the camera lens in the .db file at the time of running

Also some other people did have a successful implementation in this. Here is the link to the my notebook (https://colab.research.google.com/drive/1pRqemIwyYN-6vP0GQdiBX7uyUMUAU7QD?usp=sharing)

Here is the link to the images I was processing - 
unaltered (https://drive.google.com/drive/folders/1dOVLiSDfQrrABdsQuzJHYMjaqlXS2h4Q?usp=sharing)
compressed (https://drive.google.com/drive/folders/1q0VBaX___bZVWNrfpMotxaxR4qm42a9Q?usp=sharing)

The image worked in the local setup scenario
