### ISSUE TITLE
[question] Getting error : RuntimeError: Error on node "Meshing_1":

### ISSUE THREAD

**Issue by NoJustAnother** [alicevision/Meshroom#1637]
When running : `!./meshroom/Meshroom-2019.1.0/meshroom_photogrammetry --input ./my_dataset --output ./object_out`

I get the error:
```
11 image(s) are concerned.
[11:07:34.155139][info] CameraInit report:
	- # views listed: 11
	   - # views with an initialized intrinsic listed: 11
	   - # views without metadata (with a default intrinsic): 11
	- # intrinsics listed: 1
Nodes to execute:  ['Meshing_1', 'MeshFiltering_1', 'Texturing_1', 'Publish_1']
WARNING: downgrade status on node "Meshing_1" from Status.ERROR to Status.SUBMITTED

[1/4] Meshing
 - commandLine: aliceVision_meshing  --input "/tmp/MeshroomCache/StructureFromMotion/90d48b9689637918804eced692abda1fe94da196/sfm.abc" --depthMapsFolder "/tmp/MeshroomCache/DepthMap/dae4277878b4a44f6bc1b906b63d3956f5a77812" --depthMapsFilterFolder "/tmp/MeshroomCache/DepthMapFilter/dd7219a6989976333b174a7fb7c501cfd3d21070" --estimateSpaceFromSfM True --estimateSpaceMinObservations 3 --estimateSpaceMinObservationAngle 10 --maxInputPoints 50000000 --maxPoints 5000000 --maxPointsPerVoxel 1000000 --minStep 2 --partitioning singleBlock --repartition multiResolution --angleFactor 15.0 --simFactor 15.0 --pixSizeMarginInitCoef 2.0 --pixSizeMarginFinalCoef 4.0 --voteMarginFactor 4.0 --contributeMarginFactor 2.0 --simGaussianSizeInit 10.0 --simGaussianSize 10.0 --minAngleThreshold 1.0 --refineFuse True --addLandmarksToTheDensePointCloud False --verboseLevel info --output "/tmp/MeshroomCache/Meshing/838c7bab80ad2ebeb9a0cf526dd0f84d5c1897ec/mesh.obj" 
 - logFile: /tmp/MeshroomCache/Meshing/838c7bab80ad2ebeb9a0cf526dd0f84d5c1897ec/log
 - elapsed time: 0:00:00.036046
ERROR:root:Error on node computation: Error on node "Meshing_1":
Log:
Program called with the following parameters:
 * addLandmarksToTheDensePointCloud = 0
 * angleFactor = 15
 * contributeMarginFactor = 2
 * depthMapsFilterFolder = "/tmp/MeshroomCache/DepthMapFilter/dd7219a6989976333b174a7fb7c501cfd3d21070"
 * depthMapsFolder = "/tmp/MeshroomCache/DepthMap/dae4277878b4a44f6bc1b906b63d3956f5a77812"
 * estimateSpaceFromSfM = 1
 * estimateSpaceMinObservationAngle = 10
 * estimateSpaceMinObservations = 3
 * input = "/tmp/MeshroomCache/StructureFromMotion/90d48b9689637918804eced692abda1fe94da196/sfm.abc"
 * maxInputPoints = 50000000
 * maxPoints = 5000000
 * maxPointsPerVoxel = 1000000
 * minAngleThreshold = 1
 * minStep = 2
 * output = "/tmp/MeshroomCache/Meshing/838c7bab80ad2ebeb9a0cf526dd0f84d5c1897ec/mesh.obj"
 * partitioning =  Unknown Type "17EPartitioningMode"
 * pixSizeMarginFinalCoef = 4
 * pixSizeMarginInitCoef = 2
 * refineFuse = 1
 * repartition =  Unknown Type "16ERepartitionMode"
 * simFactor = 15
 * simGaussianSize = 10
 * simGaussianSizeInit = 10
 * universePercentile = 0.999 (default)
 * verboseLevel = "info"
 * voteMarginFactor = 4

[11:07:34.405463][info] Found 1 image dimension(s): 
[11:07:34.405600][info] 	- [1600x1200]
[11:07:34.407729][info] Overall maximum dimension: [1600x1200]
[11:07:34.407798][warning] repartitionMode: 1
[11:07:34.407808][warning] partitioningMode: 1
[11:07:34.407815][info] Meshing mode: multi-resolution, partitioning: single block.
[11:07:34.408078][info] Estimate space from SfM.
Abnormal program termination: function terminate() was called

WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Publish_1" from Status.SUBMITTED to Status.NONE
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/opt/Meshroom/setupInitScriptUnix.py", line 39, in run
  File "bin/meshroom_photogrammetry", line 125, in <module>
  File "/opt/Meshroom/meshroom/core/graph.py", line 1131, in executeGraph
  File "/opt/Meshroom/meshroom/core/node.py", line 271, in process
  File "/opt/Meshroom/meshroom/core/desc.py", line 452, in processChunk
RuntimeError: Error on node "Meshing_1":
Log:
Program called with the following parameters:
 * addLandmarksToTheDensePointCloud = 0
 * angleFactor = 15
 * contributeMarginFactor = 2
 * depthMapsFilterFolder = "/tmp/MeshroomCache/DepthMapFilter/dd7219a6989976333b174a7fb7c501cfd3d21070"
 * depthMapsFolder = "/tmp/MeshroomCache/DepthMap/dae4277878b4a44f6bc1b906b63d3956f5a77812"
 * estimateSpaceFromSfM = 1
 * estimateSpaceMinObservationAngle = 10
 * estimateSpaceMinObservations = 3
 * input = "/tmp/MeshroomCache/StructureFromMotion/90d48b9689637918804eced692abda1fe94da196/sfm.abc"
 * maxInputPoints = 50000000
 * maxPoints = 5000000
 * maxPointsPerVoxel = 1000000
 * minAngleThreshold = 1
 * minStep = 2
 * output = "/tmp/MeshroomCache/Meshing/838c7bab80ad2ebeb9a0cf526dd0f84d5c1897ec/mesh.obj"
 * partitioning =  Unknown Type "17EPartitioningMode"
 * pixSizeMarginFinalCoef = 4
 * pixSizeMarginInitCoef = 2
 * refineFuse = 1
 * repartition =  Unknown Type "16ERepartitionMode"
 * simFactor = 15
 * simGaussianSize = 10
 * simGaussianSizeInit = 10
 * universePercentile = 0.999 (default)
 * verboseLevel = "info"
 * voteMarginFactor = 4

[11:07:34.405463][info] Found 1 image dimension(s): 
[11:07:34.405600][info] 	- [1600x1200]
[11:07:34.407729][info] Overall maximum dimension: [1600x1200]
[11:07:34.407798][warning] repartitionMode: 1
[11:07:34.407808][warning] partitioningMode: 1
[11:07:34.407815][info] Meshing mode: multi-resolution, partitioning: single block.
[11:07:34.408078][info] Estimate space from SfM.
Abnormal program termination: function terminate() was called
```
I am running this on google colab - https://colab.research.google.com/github/o-date/photogrammetry/blob/master/Meshroom_%2B_GPU_for_Photogrammetry.ipynb

**Comment by ljcool2006** [comment]
I still have this issue on the Windows version.

**Comment by cbentejac** [comment]
Several versions have been released since this issue has been opened (`meshroom_photogrametry` has been replaced by `meshroom_batch`). Please open a new issue if you still run into this error with Meshroom 2025.1.0.
