### ISSUE TITLE
ValueError: not sure how to interpret line '   7       0 loop0 161 0 4696 8 304106 0 4140312 360488 0 15809 367000 0 0 0 0 421 6504\n'[question]

### ISSUE THREAD

**Issue by NoJustAnother** [alicevision/meshroom#1655]
I am trying to run Meshroom on Kaggle.

My steps:
```
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))
```

```
# get Meshroom  
!wget -N https://github.com/alicevision/meshroom/releases/download/v2019.1.0/Meshroom-2019.1.0-linux.tar.gz
!mkdir meshroom
!tar xzf Meshroom-2019.1.0-linux.tar.gz -C ./meshroom
```

```
!mkdir ./object_out
!./meshroom/Meshroom-2019.1.0/meshroom_photogrammetry --input ""../input/meshroombooks/New\ folder"" --cache ./cache --output ./object_out #-DALICEVISION_USE_ALEMBIC=ON
```

I am getting the following error:
```
Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "20EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "/tmp/tmpi9_40vqv/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm"
 * output = "/tmp/tmpi9_40vqv/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm"
 * sensorDatabase = "/kaggle/working/meshroom/Meshroom-2019.1.0/aliceVision/share/aliceVision/cameraSensors.db"
 * verboseLevel = "info"

[03:46:09.242321][warning] Some image(s) have no serial number to identify the camera/lens device.
This makes it impossible to correctly group the images by device if you have used multiple identical (same model) camera devices.
The reconstruction will assume that only one device has been used, so if 2 images share the same focal length approximation they will share the same internal camera parameters.
31 image(s) are concerned.
[03:46:09.252454][info] CameraInit report:
	- # views listed: 31
	   - # views with an initialized intrinsic listed: 31
	   - # views without metadata (with a default intrinsic): 0
	- # intrinsics listed: 1
Nodes to execute:  ['CameraInit_1', 'FeatureExtraction_1', 'ImageMatching_1', 'FeatureMatching_1', 'StructureFromMotion_1', 'PrepareDenseScene_1', 'DepthMap_1', 'DepthMapFilter_1', 'Meshing_1', 'MeshFiltering_1', 'Texturing_1', 'Publish_1']

[1/12] CameraInit
 - elapsed time: 0:00:00.002466
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
  File "/opt/Meshroom/meshroom/core/stats.py", line 206, in run
  File "/opt/Meshroom/meshroom/core/stats.py", line 200, in updateStats
  File "/opt/Meshroom/meshroom/core/stats.py", line 162, in update
  File "/opt/Meshroom/meshroom/core/stats.py", line 52, in update
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py", line 2131, in disk_io_counters
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1121, in disk_io_counters
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1094, in read_procfs
ValueError: not sure how to interpret line '   7       0 loop0 161 0 4696 8 304106 0 4140312 360488 0 15809 367000 0 0 0 0 421 6504\n'

ERROR:root:Error on node computation: [Errno 2] No such file or directory: './cache/CameraInit/238f89a37664aae5555b6681d8be0363fdaf0744//viewpoints.sfm'
WARNING: downgrade status on node "FeatureExtraction_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "ImageMatching_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureMatching_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureMatching_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "StructureFromMotion_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "PrepareDenseScene_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(10)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Publish_1" from Status.SUBMITTED to Status.NONE
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/opt/Meshroom/setupInitScriptUnix.py", line 39, in run
  File "bin/meshroom_photogrammetry", line 125, in <module>
  File "/opt/Meshroom/meshroom/core/graph.py", line 1131, in executeGraph
  File "/opt/Meshroom/meshroom/core/node.py", line 271, in process
  File "/opt/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 238, in processChunk
  File "/opt/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 228, in createViewpointsFile
FileNotFoundError: [Errno 2] No such file or directory: './cache/CameraInit/238f89a37664aae5555b6681d8be0363fdaf0744//viewpoints.sfm'
```

My Kaggle link - https://www.kaggle.com/onetooth/meshroomtry

How do I solve this?

**Comment by UranusSeven** [comment]
Similar error when running on google colab.

Way to reproduce:

![image](https://user-images.githubusercontent.com/109661872/215272148-f56e6faf-ed46-4ec7-a84a-490aca2cabbd.png)

**Comment by thevaibhavkute** [comment]
Same error

**Comment by l3afai** [comment]
Any way on how to fix this?

**Comment by Harsh19012003** [comment]
similar error, I am trying to run it on google colab, i even use my own images as well as by default buddha images as suggested in notebook......Has anyone fixed it yet??
