### ISSUE TITLE
[question] Is it possible or how to "Clear Pending Status" from the command line?

### ISSUE THREAD

**Issue by DGruenwald** [alicevision/Meshroom#1847]
**Describe the problem**
I am trying to use meshroom_compute on a (free) Google Colab instance. I believe I have everything set up correctly and it is mostly working. However, due to the usage limits, I can't do everything in one go, and when I try to resume, it just prints an error that there are no nodes to be processed (even with ```--forceStatus```).

After doing a little research, I assume that this is because the status of the tasks in the cache folder is set to 'SUBMITTED', which the "Clear Pending Status" function would apparently fix. However, since I'm on Google Colab, I can't use the GUI.

So my question is, can you do "Clear Pending Status" from the command line?

Alternatively, what does the "Clear Pending Status" operation actually do? If it's just setting the 'status' property in the '#.status' JSON files from 'SUBMITTED' to 'NONE' or something, then I can very easily just modify the files myself.

By the way, as a workaround, I am currently manually specifying the next node to compute with the ```--node``` argument, but that's not ideal, since I need to know the full names and correct sequence of the nodes, and it doesn't automatically move on to the next (```--toNode``` gives the same ```Impossible Process``` error).

**Log**
```
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/opt/Meshroom/setupInitScriptUnix.py", line 39, in run
  File "bin/meshroom_compute", line 71, in <module>
  File "/opt/Meshroom/meshroom/core/taskManager.py", line 192, in compute
  File "/opt/Meshroom/meshroom/core/taskManager.py", line 368, in raiseImpossibleProcess
RuntimeError: [COMPUTATION] Impossible Process:
There is no node able to be processed.
```

Using Meshroom-2021.1.0 (Meshroom-2021.1.0-linux-cuda10.tar.gz) on Google Colab runtime.

**Comment by DGruenwald** [comment]
Nevermind, I've finished my project with the workaround I mentioned. It may still be good to know for the future, though!

**Comment by cbentejac** [comment]
Hi,
 
Many things have changed with `meshroom_compute` / `meshroom_batch` since the 2021 release, but in your case I believe using `--forceCompute` would have done the trick. Glad you still managed to go through with your project!
