### ISSUE TITLE
[bug] Failure to launch on linux

### ISSUE THREAD

**Issue by gentlecolts** [alicevision/Meshroom#1891]
Manjaro, meshroom installed from official repositories, crashes immediately with the following:

```
Traceback (most recent call last):
  File "/usr/bin/meshroom", line 12, in <module>
    from meshroom.ui.app import MeshroomApp
  File "/usr/lib/python3.10/meshroom/ui/app.py", line 7, in <module>
    from PySide2.QtWidgets import QApplication
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
ImportError: /usr/lib/python3.10/site-packages/PySide2/QtWidgets.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN11QToolButton13checkStateSetEv, version Qt_5
```

**Comment by lenghonglin** [comment]
the same with you
