### ISSUE TITLE
[bug]Meshroom ne demarre pas sous ubuntu 22.04

### ISSUE THREAD

**Issue by Web793** [alicevision/Meshroom#1895]
./Meshroom 
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 39, in run
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/opt/Meshroom/setupInitScriptUnix.py", line 27, in <module>
OSError: [Errno 7] Argument list too long

**Comment by 2233431914** [comment]
Have you tried to change the files' path? I had the same problem yesterday,I thought about my Chinese string path,maybe wasn't about it,but I changed my path, and then succeed.
