### ISSUE TITLE
[bug] No node being able to be processed

### ISSUE THREAD

**Issue by mcDandy** [alicevision/Meshroom#1907]
**Describe the bug**
It is not possible to finish meshing, becouse there is no tasks scheduled.

**To Reproduce**
1. start dense reconstruction with about 700 images 2160x3840
2. Wait multiple days
3. get "Abnormal program termination: received signal 21 (SIGBREAK)" messange in meshing stage
4. click resume

**Expected behavior**
Node would star over (same as on any other error)

**Screenshots**
![image](https://user-images.githubusercontent.com/18588943/221371146-11aeadee-360d-47e3-b226-be19ec282d7e.png)

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )
Output of program
```
WARNING:root:Retrying to obtain clipboard.
WARNING:root:Retrying to obtain clipboard.
WARNING:root:Retrying to obtain clipboard.
Traceback (most recent call last):
  File "d:\release\BUILD\meshroom\meshroom\ui\graph.py", line 384, in execute
  File "d:\release\BUILD\meshroom\meshroom\core\taskManager.py", line 192, in compute
  File "d:\release\BUILD\meshroom\meshroom\core\taskManager.py", line 368, in raiseImpossibleProcess
RuntimeError: [COMPUTATION] Impossible Process:
There is no node able to be processed.
```
Node output
```
Program called with the following parameters:
 * addLandmarksToTheDensePointCloud = 0
 * angleFactor = 15
 * colorizeOutput = 0
 * contributeMarginFactor = 2
 * densifyNbBack = 0 (default)
 * densifyNbFront = 0 (default)
 * densifyScale = 1 (default)
 * depthMapsFolder = "d:/Users/Daniel N/Documents/vila/MeshroomCache/DepthMapFilter/6498139893da7beace7dcdf3c9cb639c375d3920"
 * estimateSpaceFromSfM = 1
 * estimateSpaceMinObservationAngle = 10
 * estimateSpaceMinObservations = 3
 * exportDebugTetrahedralization = 0
 * fullWeight = 1
 * helperPointsGridSize = 10
 * input = "d:/Users/Daniel N/Documents/vila/MeshroomCache/StructureFromMotion/44ada9cb7612523703a035d122b796e1978af930/sfm.abc"
 * invertTetrahedronBasedOnNeighborsNbIterations = 10
 * maskBorderSize = 1 (default)
 * maskHelperPointsWeight = 0 (default)
 * maxInputPoints = 50000000
 * maxNbConnectedHelperPoints = 50
 * maxPoints = 5000000
 * maxPointsPerVoxel = 1000000
 * minAngleThreshold = 1
 * minSolidAngleRatio = 0.2
 * minStep = 2
 * minVis = 2 (default)
 * nPixelSizeBehind = 4
 * nbSolidAngleFilteringIterations = 2
 * output = "d:/Users/Daniel N/Documents/vila/MeshroomCache/Meshing/e53a95385653082171f29a9b65e6f4d3ff7aa3a1/densePointCloud.abc"
 * outputMesh = "d:/Users/Daniel N/Documents/vila/MeshroomCache/Meshing/e53a95385653082171f29a9b65e6f4d3ff7aa3a1/mesh.obj"
 * partitioning =  Unknown Type "enum EPartitioningMode"
 * pixSizeMarginFinalCoef = 4
 * pixSizeMarginInitCoef = 2
 * refineFuse = 1
 * repartition =  Unknown Type "enum ERepartitionMode"
 * saveRawDensePointCloud = 0
 * seed =  Unknown Type "unsigned int"
 * simFactor = 15
 * simGaussianSize = 10
 * simGaussianSizeInit = 10
 * universePercentile = 0.999 (default)
 * verboseLevel = "info"
 * voteFilteringForWeaklySupportedSurfaces = 1
 * voteMarginFactor = 4

[21:27:32.005924][info] Found 1 image dimension(s): 
[21:27:32.006925][info] 	- [2160x3840]
[21:27:47.814341][info] Overall maximum dimension: [2160x3840]
[21:27:47.814341][warning] repartitionMode: 1
[21:27:47.814341][warning] partitioningMode: 1
[21:27:47.814341][info] Meshing mode: multi-resolution, partitioning: single block.
[21:27:48.172993][info] Estimate space from SfM.
[21:27:52.937556][info] Estimate space done.
[21:27:52.937556][info] bounding Box : length: 4.02194, width: 6.75081, height: 5.60841
[21:27:56.064586][info] Creating dense point cloud.
[21:27:56.065586][info] fuseFromDepthMaps, maxVertices: 5000000
[21:27:57.384277][info] simFactor: 15
[21:27:57.384277][info] nbPixels: 4196966400
[21:27:57.384277][info] maxVertices: 5000000
[21:27:57.384277][info] step: 9
[21:27:57.384277][info] realMaxVertices: 51733440
[21:27:57.384277][info] minVis: 2
[21:27:57.384277][info] Load depth maps and add points.
[21:37:23.894032][info] Filter initial 3D points by pixel size to remove duplicates.
[21:37:27.290747][info] Build nanoflann KdTree index.
[21:38:41.560511][info] KdTree created for 51733440 points.
[21:38:48.441665][info] Filtering done.
[21:38:49.492010][info] 46542853 invalid points removed.
[21:38:49.988469][info] 3D points loaded and filtered to 5190587 points.
[21:38:49.988469][info] Init visibilities to compute angle scores
[21:38:59.279838][info] NANOFLANN: KdTree created.
[21:39:01.494018][info] Create visibilities (0/506)
[21:39:01.495018][info] Create visibilities (338/506)
[21:39:01.495018][info] Create visibilities (169/506)
[21:39:07.039064][info] Create visibilities (339/506)
[21:39:07.609255][info] Create visibilities (170/506)
[21:39:09.226293][info] Create visibilities (1/506)
[21:39:10.815253][info] Create visibilities (340/506)
[21:39:11.463736][info] Create visibilities (171/506)
[21:39:12.243641][info] Create visibilities (2/506)
[21:39:15.125089][info] Create visibilities (341/506)
...
[21:52:31.959220][info] Create visibilities (504/506)
[21:52:34.024931][info] Create visibilities (337/506)
[21:52:35.712645][info] Create visibilities (505/506)
[21:52:44.705714][info] Visibilities created.
[21:52:44.765714][info] Compute max angle per point
[21:52:44.765714][info] angleFactor: 15
[21:55:15.231312][info] 0 points filtered based on the number of observations (minVis). 
[21:55:20.703012][info] 331602 invalid points removed.
[21:55:25.941470][info] Filter by angle score and sim score
[21:55:25.941470][info] Build nanoflann KdTree index.
[21:55:34.803373][info] KdTree created for 4858985 points.
[21:55:38.386438][info] Filtering done.
[21:55:40.940844][info] 2082828 invalid points removed.
[21:55:43.728598][info] The number of points is below the max number of vertices.
[21:55:43.729598][info] 3D points loaded and filtered to 2776157 points (maxVertices is 5000000).
[21:55:43.729598][info] Create final visibilities
[21:55:48.482776][info] NANOFLANN: KdTree created.
[21:55:51.143221][info] Create visibilities (0/506)
[21:55:51.144222][info] Create visibilities (169/506)
[21:55:51.145223][info] Create visibilities (338/506)
[21:55:57.726774][info] Create visibilities (339/506)
[21:55:58.250243][info] Create visibilities (1/506)
...
[22:08:56.782312][info] Create visibilities (337/506)
[22:09:03.074032][info] Visibilities created.
[22:09:03.115204][warning] fuseFromDepthMaps done: 2776157 points created.
[22:09:03.118206][warning] Add 506 new points for the 506 cameras centers.
[22:09:03.119206][warning] Add 6 points to prevent singularities
[22:09:03.121716][warning] Add 1331 new helper points for a 3D grid of 10x10x10.
[22:09:03.310463][warning] Final dense point cloud: 2778000 points.
[22:10:30.998205][info] 18353855 cells created by tetrahedralization.
[22:14:29.352519][info] coutInvalidVertices: 0
[22:14:29.353518][info] neighboringCellsPerVertexTmp: 2778000
[22:14:29.426299][info] verticesCoords: 2778000
[22:16:25.930670][info] DelaunayGraphCut::voteFullEmptyScore
[22:16:25.968817][info] nPixelSizeBehind: 4
[22:16:25.968817][info] DelaunayGraphCut::displayCellsStats
[22:16:26.490280][info]  [acc_nrc] min: 0 max: 1563 mean: 107.689 median: 83.7112
[22:16:26.490280][info]  [acc_camSize] min: 0 max: 198 mean: 29.9419 median: 21.9411
[22:16:39.439282][info]  [cellScore] min: 0 max: 0 mean: 0 median: 0
[22:16:39.439282][info]  [cellSWeight] min: 0 max: 0 mean: 0 median: 0
[22:16:39.439282][info]  [cellTWeight] min: 0 max: 0 mean: 0 median: 0
[22:16:39.442283][info]  [gEdgeVisWeight] min: 0 max: 0 mean: 0 median: 0
[22:16:39.442283][info]  [fullnessScore] min: 0 max: 0 mean: 0 median: 0
[22:16:39.442283][info]  [emptinessScore] min: 0 max: 0 mean: 0 median: 0
[22:16:39.442283][info]  [on] min: 0 max: 0 mean: 0 median: 0
[22:16:39.442283][info] countPositiveSWeight: 0
[22:16:39.457350][info] Computing s-t graph weights.
fillGraphPartPtRc
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[23:28:24.899020][info] DelaunayGraphCut::displayCellsStats
[23:28:25.502686][info]  [acc_nrc] min: 0 max: 1563 mean: 107.689 median: 83.7112
[23:28:25.502686][info]  [acc_camSize] min: 0 max: 198 mean: 29.9419 median: 21.9411
[23:28:43.687174][info]  [cellScore] min: -87812 max: 1e+06 mean: 71526 median: -4037.53
[23:28:43.688177][info]  [cellSWeight] min: 0 max: 1e+06 mean: 71682.6 median: 0.012262
[23:28:43.688177][info]  [cellTWeight] min: 0 max: 87812 mean: 707.86 median: 0.00024001
[23:28:43.688177][info]  [gEdgeVisWeight] min: 0 max: 2.71277e+08 mean: 28243.4 median: 16.5164
[23:28:43.688177][info]  [fullnessScore] min: 0 max: 107332 mean: 1245.47 median: 0.000617609
[23:28:43.688177][info]  [emptinessScore] min: 0 max: 2.91966e+08 mean: 117812 median: 2085.7
[23:28:43.688177][info]  [on] min: 0 max: 86394 mean: 707.426 median: 0.000282942
[23:28:43.688177][info] countPositiveSWeight: 1310991
[23:28:44.155397][warning] DelaunayGraphCut::addToInfiniteSw nbInfinitCells: 0
[23:28:44.155397][info] DelaunayGraphCut::displayCellsStats
[23:28:44.772685][info]  [acc_nrc] min: 0 max: 1563 mean: 107.689 median: 83.7112
[23:28:44.772685][info]  [acc_camSize] min: 0 max: 198 mean: 29.9419 median: 21.9411
[23:29:02.326953][info]  [cellScore] min: -87812 max: 1e+06 mean: 71526 median: -4037.53
[23:29:02.326953][info]  [cellSWeight] min: 0 max: 1e+06 mean: 71682.6 median: 0.012262
[23:29:02.326953][info]  [cellTWeight] min: 0 max: 87812 mean: 707.86 median: 0.00024001
[23:29:02.326953][info]  [gEdgeVisWeight] min: 0 max: 2.71277e+08 mean: 28243.4 median: 16.5164
[23:29:02.326953][info]  [fullnessScore] min: 0 max: 107332 mean: 1245.47 median: 0.000617609
[23:29:02.326953][info]  [emptinessScore] min: 0 max: 2.91966e+08 mean: 117812 median: 2085.7
[23:29:02.326953][info]  [on] min: 0 max: 86394 mean: 707.426 median: 0.000282942
[23:29:02.326953][info] countPositiveSWeight: 1310991
[23:29:02.326953][info] Forcing t-edges
[23:39:03.930450][info] DelaunayGraphCut::displayCellsStats
[23:39:04.435344][info]  [acc_nrc] min: 0 max: 1563 mean: 107.689 median: 83.7112
[23:39:04.436345][info]  [acc_camSize] min: 0 max: 198 mean: 29.9419 median: 21.9411
[23:39:20.739238][info]  [cellScore] min: -1e+06 max: 1e+06 mean: 71442 median: -5321.1
[23:39:20.739238][info]  [cellSWeight] min: 0 max: 1e+06 mean: 71682.6 median: 0.012262
[23:39:20.741237][info]  [cellTWeight] min: 0 max: 1e+06 mean: 784.24 median: 5.73134e-05
[23:39:20.741237][info]  [gEdgeVisWeight] min: 0 max: 2.71277e+08 mean: 28243.4 median: 16.5164
[23:39:20.741237][info]  [fullnessScore] min: 0 max: 107332 mean: 1245.47 median: 0.000617609
[23:39:20.741237][info]  [emptinessScore] min: 0 max: 2.91966e+08 mean: 117812 median: 2085.7
[23:39:20.742238][info]  [on] min: 0 max: 1.07545e+07 mean: 5.82507 median: 9.36911e-05
[23:39:20.742238][info] countPositiveSWeight: 1310991
[23:39:20.742238][info] Maxflow: start allocation.
[23:39:20.742238][info] Number of cells: 18353855
[23:39:39.813247][info] Maxflow: add nodes.
[23:40:06.523365][info] Maxflow: 1310976 S cells, 17042879 T cells.
[23:40:06.523365][info] Maxflow: add edges.
Abnormal program termination: received signal 21 (SIGBREAK)

```

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ] Windows 11
 - Python version [e.g. 2.6] 3.9 (meshroom says 3.7.4)
 - Qt/PySide version [e.g. 5.12.4] Bundled with Meshroom 2021.1. I cannot gwt more specific than 5.
 - Meshroom version: please specify if you are using a release version or your own build release
   - Binary version (if applicable) [e.g. 2019.1] 2021.1
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**
CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.21 GHz
RAM: 16GB
GPU: NVIDIA Quadro P1000 (4GB VRAM)

Project: [project.zip](https://github.com/alicevision/Meshroom/files/10831893/project.zip)

**Comment by cbentejac** [comment]
This occurs when all the nodes already have either a "computed" or a "submitted" status. Here, the error on the Meshing node stopped the computation but the status of the following nodes was not reset. 

Whenever this happens, using the "Clear Pending Status" allows to reset the status of all the "submitted" nodes, thus making them computable again.

![Image](https://github.com/user-attachments/assets/1a72edaa-5322-4cc8-8355-a9ed5253bbc6)
