### ISSUE TITLE
when I shutdown my computer and reopen meshroom , click"start", it encountered "RuntimeError: [COMPUTATION] Impossible Process: There is no node able to be processed."

### ISSUE THREAD

**Issue by geographerwang** [alicevision/Meshroom#1949]
### **Describe the problem**
the problem as follows:
Traceback (most recent call last):
  File "d:\release\BUILD\meshroom\meshroom\ui\reconstruction.py", line 477, in onCameraInitChanged
  File "d:\release\BUILD\meshroom\meshroom\ui\reconstruction.py", line 971, in setActiveNodes
  File "d:\release\BUILD\meshroom\meshroom\ui\reconstruction.py", line 1023, in setSfm
  File "d:\release\BUILD\meshroom\meshroom\ui\reconstruction.py", line 1006, in _setSfm
  File "d:\release\BUILD\meshroom\meshroom\ui\reconstruction.py", line 987, in updateSfMResults
  File "d:\release\BUILD\meshroom\meshroom\ui\reconstruction.py", line 380, in parseSfMJsonFile
  File "C:\Program Files\Python37\lib\json\__init__.py", line 293, in load
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 845: illegal multibyte sequence
Traceback (most recent call last):
  File "d:\release\BUILD\meshroom\meshroom\ui\reconstruction.py", line 555, in onGraphChanged
  File "d:\release\BUILD\meshroom\meshroom\ui\reconstruction.py", line 1021, in setSfm
RuntimeError: Failed to disconnect signal statusChanged().
WARNING:root:Model size of -13 is less than 0
Traceback (most recent call last):
  File "d:\release\BUILD\meshroom\meshroom\ui\graph.py", line 384, in execute
  File "d:\release\BUILD\meshroom\meshroom\core\taskManager.py", line 192, in compute
  File "d:\release\BUILD\meshroom\meshroom\core\taskManager.py", line 368, in raiseImpossibleProcess
RuntimeError: [COMPUTATION] Impossible Process:
There is no node able to be processed.
Traceback (most recent call last):
  File "d:\release\BUILD\meshroom\meshroom\ui\graph.py", line 384, in execute
  File "d:\release\BUILD\meshroom\meshroom\core\taskManager.py", line 192, in compute
  File "d:\release\BUILD\meshroom\meshroom\core\taskManager.py", line 368, in raiseImpossibleProcess
RuntimeError: [COMPUTATION] Impossible Process:
There is no node able to be processed.
WARNING:root:Retrying to obtain clipboard.
**Screenshots**
![image](https://user-images.githubusercontent.com/12079968/227889462-3bc03b13-9bb3-4ac8-bc32-a0c21949c3b6.png)

**Comment by geographerwang** [comment]
it seems that the process "aliceVision_depthMapEstimation.exe" is already running. first click stop,then click start,it becomes normal.
