### ISSUE TITLE
[bug] Meshroom do not start under Fedora 38

### ISSUE THREAD

**Issue by AFCMS** [alicevision/Meshroom#2050]
**Describe the bug**
Using the official release archive and crashing at start-up.

**To Reproduce**
1. Use Fedora 38 (didn't test running Meshroom on any other modern Linux distro, working fine on Windows)
2. Download the official archive from the website
3. Unarchive the file
4. Try to run the `Meshroom` binary file in terminal
5. See error

**Expected behavior**
It should not crash.

**Screenshots**

**Log**
```
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 39, in run
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/opt/Meshroom/setupInitScriptUnix.py", line 27, in <module>
OSError: [Errno 7] Argument list too long
```

The `/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py` file do not exist on my system, so I guess Meshroom binaries run in some kind of sandbox?

**Desktop (please complete the following and other pertinent information):**
 - OS: Fedora 38
 - Python version: 3.11.3 and 2.7.18 installed
 - Qt/PySide version: 5.15.9 and 6.5.1 installed, don't think PySide is relevant here since its a release build
 - Meshroom version: 2023.1.0 (release version)

**Additional context**
None

**Comment by EstebanDugueperoux2** [comment]
I have succeed to start meshroom directly by invoking start.sh from source.

**Comment by AFCMS** [comment]
I managed to get it working from source. Was difficult since latest python versions are unsupported so I had to install specifically 3.8 on my system.

But the official binary isn't working yet sadly.

I really hope there will be a flatpak or something like this to make it easier to support many linux distros.
