### ISSUE TITLE
[question] running meshroom_batch creates uid conflict on linux

### ISSUE THREAD

**Issue by Kidney-02** [alicevision/Meshroom#2102]
**Describe the problem**
running meshroom_batch command:
meshroom_batch --i /media/user/HDD/Meshroom/Inputs/Processed --save /media/user/HDD/Meshroom/Caches/test.mg
creates no uids, and if i try to run meshroom_compute on this save it crashes
in the save file uid for every node is just absent and if i open it in meshroom every node has a warning that asks to update node

**Dataset**
I just used 3 images i took of the ground, they compute perfectly fine using gui.

**Log**
$ ./meshroom_compute /media/user/HDD/Meshroom/Caches/test.mg
WARNING:root:Compatibility issue detected for node 'Texturing_1': UidConflict
WARNING:root:Compatibility issue detected for node 'Meshing_1': UidConflict
WARNING:root:Compatibility issue detected for node 'DepthMapFilter_1': UidConflict
WARNING:root:Compatibility issue detected for node 'ImageMatching_1': UidConflict
WARNING:root:Compatibility issue detected for node 'FeatureExtraction_1': UidConflict
WARNING:root:Compatibility issue detected for node 'StructureFromMotion_1': UidConflict
WARNING:root:Compatibility issue detected for node 'PrepareDenseScene_1': UidConflict
WARNING:root:Compatibility issue detected for node 'CameraInit_1': UidConflict
WARNING:root:Compatibility issue detected for node 'DepthMap_1': UidConflict
WARNING:root:Compatibility issue detected for node 'MeshFiltering_1': UidConflict
WARNING:root:Compatibility issue detected for node 'FeatureMatching_1': UidConflict
WARNING:root:Invalid expression with missing key on "CameraInit_1.output" with value "{cache}/{nodeType}/{uid0}/cameraInit.sfm".
Error: 'uid0'
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/opt/Meshroom/setupInitScriptUnix.py", line 42, in run
  File "bin/meshroom_compute", line 34, in <module>
  File "/opt/Meshroom/meshroom/core/graph.py", line 1523, in loadGraph
  File "/opt/Meshroom/meshroom/common/core.py", line 112, in func_wrapper
  File "/opt/Meshroom/meshroom/core/graph.py", line 317, in load
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/contextlib.py", line 88, in __exit__
  File "/opt/Meshroom/meshroom/core/graph.py", line 55, in GraphModification
  File "/opt/Meshroom/meshroom/core/graph.py", line 487, in updateEnabled
  File "/opt/Meshroom/meshroom/core/graph.py", line 1387, in update
  File "/opt/Meshroom/meshroom/core/graph.py", line 1352, in updateInternals
  File "/opt/Meshroom/meshroom/core/node.py", line 902, in updateInternals
  File "/opt/Meshroom/meshroom/core/node.py", line 910, in internalFolder
KeyError: 'uid0'

**Desktop (please complete the following and other pertinent information):**
 - OS: Linux Mint 21.1 Vera
 - Python version: 3.10.6
 - Qt/PySide version 5.15.9
 - Meshroom version: Meshroom-2023.2.0-av3.1.0-centos7-cuda11.3.1

**Additional context**
I found this issue making this:
https://github.com/Kidney-02/Meshroom_Batch_Processor
I wrote it on windows. It was throwing uid error when running meshroom_compute, but it would still finish and the .mg file had uid numbers. Opening the .mg file in meshroom only the last 2 nodes have the warning that asks to upgrade

**Comment by cbentejac** [comment]
Hi @Kidney-02,

This looks very similar to the issue solved by https://github.com/alicevision/Meshroom/pull/2095: the bug itself is the same, the only difference is that it was triggered by using the `--submit` option. I think your issue will be solved by it as well.

It is already available on the `develop` branch and will be part of the next release.

**Comment by Kidney-02** [comment]
thnx
