### ISSUE TITLE
ERROR: unrecognised option '--maxNbImagesForFusion'

### ISSUE THREAD

**Issue by abszolut** [alicevision/meshroom#212]
Hi I have got this error by running mesh with command line:

WARNING: downgrade status on node "Publish_1" from Status.SUBMITTED to Status.NONE
Traceback (most recent call last):
  File "bin/meshroom_photogrammetry", line 64, in <module>
    meshroom.core.graph.executeGraph(graph, toNodes=toNodes, forceCompute=args.forceCompute, forceStatus=args.forceStatus)
  File "C:\Users\abszolut\Repos\meshroom-develop\meshroom\core\graph.py", line 1124, in executeGraph
    chunk.process(forceCompute)
  File "C:\Users\abszolut\Repos\meshroom-develop\meshroom\core\node.py", line 271, in process
    self.node.nodeDesc.processChunk(self)
  File "C:\Users\abszolut\Repos\meshroom-develop\meshroom\core\desc.py", line 407, in processChunk
    raise RuntimeError('Error on node "{}":\nLog:\n{}'.format(chunk.name, logContent))
RuntimeError: Error on node "Texturing_1":
Log:
ERROR: unrecognised option '--maxNbImagesForFusion'

Thank for helping.

**Comment by fabiencastan** [comment]
Are you using the pre-built binaries (from the github release)?
If not, you probably need to update the AliceVision repository.
