### ISSUE TITLE
question: launch a 3D reconstruction in command line (can not connect AliceVision)

### ISSUE THREAD

**Issue by shaoxiang777** [alicevision/Meshroom#2315]
**My problem**

Hello all,
thanks for opening the source of Meshroom! I have some problem to **launch a 3D reconstruction in command line** on linux 22.04
`PYTHONPATH=$PWD python bin/meshroom_batch --input INPUT_IMAGES_FOLDER --output OUTPUT_FOLDER`

1. I have compile and build AliceVision following [INSTALL.md](https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md) successfully, but I dont know how to conect with Meshroom.

```
git clone https://github.com/alicevision/AliceVision.git --recursive
mkdir build && cd build
cmake -DALICEVISION_BUILD_DEPENDENCIES=ON -DCMAKE_INSTALL_PREFIX=$PWD/../install ../AliceVision
make -j10 
```

```
/home/jonas/ 
      |__ AliceVision
      |__ build
      |__ install
          |__ bin
          |__ include
          |__ lib
          |__ share
```

2. Set the alicevision paths (enter the following in the terminal)
```
ALICEVISION_SENSOR_DB=/home/jonas/AliceVision/src/aliceVision/sensorDB/cameraSensors.db
ALICEVISION_VOCTREE=/home/jonas/AliceVision/model/vlfeat_K80L3.SIFT.tree
ALICEVISION_SPHERE_DETECTION_MODEL=/home/jonas/AliceVision/model/sphereDetection_Mask-RCNN.onnx
ALICEVISION_SEMANTIC_SEGMENTATION_MODEL=/home/jonas/AliceVision/model/fcn_resnet50.onnx
ALICEVISION_ROOT=/home/jonas/install
PATH=$PATH:${ALICEVISION_ROOT}/bin
PYTHONPATH=/home/jonas/Meshroom
```
3. compile Meshroom
```
git clone --recursive git://github.com/alicevision/meshroom
cd meshroom
pip install -r requirements.txt
```

4. launch the code in command line
```
cd /home/jonas/Meshroom
PYTHONPATH=$PWD python bin/meshroom_batch --input /home/jonas/Meshroom/dataset/imgs --output home/jonas/Meshroom/dataset/output
```

**Problem Screenshots**

```
(meshroom) jonas@jonas:~/Meshroom (develop)$ PYTHONPATH=$PWD python bin/meshroom_batch --input /home/jonas/Meshroom/dataset/imgs --output /home/jonas/Meshroom/dataset/output
WARNING:root:== The following "submitters" plugins could not be loaded ==
  * rippleSubmitter: No module named 'mpc'
  * simpleFarmSubmitter: No module named 'simpleFarm'

aliceVision_cameraInit: error while loading shared libraries: libboost_filesystem.so.1.80.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "bin/meshroom_batch", line 158, in <module>
    initNode.nodeDesc.initialize(initNode, inp, inpRec)
  File "/home/jonas/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 359, in initialize
    views, intrinsics = self.buildIntrinsics(node, filesByType.images)
  File "/home/jonas/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 421, in buildIntrinsics
    proc.returncode, cmd)
RuntimeError: CameraInit failed with error code 127.
Command was: "aliceVision_cameraInit  --sensorDatabase "/home/jonas/AliceVision/src/aliceVision/sensorDB/cameraSensors.db" --lensCorrectionProfileInfo "${ALICEVISION_LENS_PROFILE_INFO}" --lensCorrectionProfileSearchIgnoreCameraModel True --defaultFieldOfView 45.0 --groupCameraFallback "folder" --allowedCameraModels "pinhole,radial1,radial3,brown,fisheye4,fisheye1,3deanamorphic4,3deradial4,3declassicld" --rawColorInterpretation "LibRawWhiteBalancing" --viewIdMethod "metadata" --verboseLevel "info" --output "/tmp/tmpt6uxzn1s/CameraInit/961e54591174ec5a2457c66da8eadc0cb03d89ba/cameraInit.sfm" --allowSingleView 1 --input "/tmp/tmpt6uxzn1s/CameraInit/961e54591174ec5a2457c66da8eadc0cb03d89ba/viewpoints.sfm"".

```

**Desktop :**
 - OS: [linux 22.04 ]
 - Python version [3.7]
 - Qt/PySide version [not installed]
 - Meshroom version: latest Meshroom 2024.1.0-develop

**Additional context**
In terminal it mentions `aliceVision_cameraInit: error while loading shared libraries: libboost_filesystem.so.1.80.0`, actually **libboost_filesystem.so.1.80.0** can be found in install/lib and build/boost/stage/lib

What should I do and what I missed? I have checked [issue 198](https://github.com/alicevision/meshroom/issues/198) and [issue 2198](https://github.com/alicevision/Meshroom/issues/2198), which are relevant to my case.

Thanks a lot in advance!
Jonas

**Comment by olelukoje** [comment]
Hello!

I had the same error, it helped me to set LD_LIBRARY_PATH variable:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${ALICEVISION_ROOT}/lib`
