### ISSUE TITLE
meshroom_batch change Texturing.colorMappingFileType syntax

### ISSUE THREAD

**Issue by Arwa45** [alicevision/Meshroom#2321]
Using the command line tool "meshroom_batch" I am unable to override parameters like the "colorMappingFileType" 

**To Reproduce**
I follow those steps:
1. I open meshroom from cmd and insert the following command:  meshroom_batch -i "input file path" 
which works, but outputs the texturing file as "exr", I want it to output it as "png"
2. I try the following cmd:  meshroom_batch -i "input file path"  --paramOverrides Texturing.colorMappingFileType=png
which outputs the following error:
KeyError: 'colorMappingFileType'
 I try the following cmd:  meshroom_batch -i "input file path"  --paramOverrides Texturing.textureFileType=png
which outputs the following error:
KeyError: 'textureFileType'

Error as shown in cmd:

Overrides Texturing.textureFileType=png
Traceback (most recent call last):
  File "C:\Release\sources\Meshroom\venv\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Release\sources\Meshroom\venv\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
  File "bin/meshroom_batch", line 201, in <module>
  File "C:\Release\sources\Meshroom\meshroom\common\core.py", line 112, in func_wrapper
  File "C:\Release\sources\Meshroom\meshroom\core\node.py", line 607, in attribute
  File "C:\Release\sources\Meshroom\meshroom\common\core.py", line 36, in get
KeyError: 'textureFileType'

**Comment by Arwa45** [comment]
> Hi @Arwa45,
> 
> You're almost there! The right command would be: `meshroom_batch -i "input file path" --paramOverrides Texturing.colorMapping.colorMappingFileType="png"`
> 
> This is because the `colorMappingFileType` attribute is part of the `colorMapping` group attribute, so the full reference is needed to override its value. `textureFileType` is not a valid attribute for the Texturing node, which explains the second error.
> 
> Please let me know if that fixes your issue.

Thanks alot, this worked.
