### ISSUE TITLE
Meshroom process doesn't start -FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ChrisM2017** [alicevision/Meshroom#2438]
My computer previously ran meshroom perfectly well, but now seems unable to run the process. I open the program, save the file to the required folder, and load some images. When I hit start, however, nothing happens, and the file not found error message appears in the log (example copied below). 
A clear and concise description of what the problem is.

![image](https://github.com/alicevision/Meshroom/assets/172888830/0b8f42e0-e970-4d22-9e32-904e2dd38c9d)

![P7110713](https://github.com/alicevision/Meshroom/assets/172888830/2378d035-4d43-4c75-ad0b-4ada890259b4)
![P7120714](https://github.com/alicevision/Meshroom/assets/172888830/642f7699-8035-49ab-ac11-2954c1ff2fca)
![Uploading P7130715.JPG…]()

If applicable, add a link or *few* images to help better understand where the problem may come from.

[2024-06-15 09:03:22.687045] [0x00001178] [trace]   Embedded OCIO configuration file: 'C:\Program Files\Meshroom-2023.3.0\aliceVision/share/aliceVision/config.ocio' found.
[QtAliceVisionImageIO] Plugin Initialized
[QtAliceVision] Plugin Initialized
[2024-06-15 09:04:51.176701] [0x000034e8] [trace]   Embedded OCIO configuration file: 'C:\Program Files\Meshroom-2023.3.0\aliceVision/share/aliceVision/config.ocio' found.
Program called with the following parameters:
 * allowSingleView = 1
 * allowedCameraModels = "pinhole,radial1,radial3,brown,fisheye4,fisheye1,3deanamorphic4,3deradial4,3declassicld"
 * colorProfileDatabase = "" (default)
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLength = -1 (default)
 * defaultFocalRatio = 1 (default)
 * defaultOffsetX = 0 (default)
 * defaultOffsetY = 0 (default)
 * errorOnMissingColorProfile = 1 (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:\Users\User\AppData\Local\Temp\tmpq6f_y4rx/CameraInit/961e54591174ec5a2457c66da8eadc0cb03d89ba/viewpoints.sfm"
 * lensCorrectionProfileInfo = "${ALICEVISION_LENS_PROFILE_INFO}"
 * lensCorrectionProfileSearchIgnoreCameraModel = 1
 * maxCoresAvailable =  Unknown Type "unsigned int" (default)
 * maxMemoryAvailable = 18446744073709551615 (default)
 * output = "C:/Users/User/AppData/Local/Temp/tmpq6f_y4rx/CameraInit/961e54591174ec5a2457c66da8eadc0cb03d89ba/cameraInit.sfm"
 * rawColorInterpretation =  Unknown Type "enum aliceVision::image::ERawColorInterpretation"
 * sensorDatabase = "C:\Program Files\Meshroom-2023.3.0\aliceVision\share\aliceVision\cameraSensors.db"
 * verboseLevel = "info"
 * viewIdMethod =  Unknown Type "enum aliceVision::sfmDataIO::EViewIdMethod"
 * viewIdRegex = ".*?(\d+)" (default)

Hardware :
        Detected core count : 16
        OpenMP will use 16 cores
        Detected available memory : 25404 Mo

[09:04:51.320335][info] 0 profile(s) stored in the LCP database.
[09:04:51.501270][warning] Some image(s) have no serial number to identify the camera/lens device.
This makes it impossible to correctly group the images by device if you have used multiple identical (same model) camera devices.
The reconstruction will assume that only one device has been used, so if 2 images share the same focal length approximation they will share the same internal camera parameters.
5 image(s) are concerned.
[09:04:51.509574][info] CameraInit report:
        - # Views: 9
           - # with focal length initialization (from metadata): 9
           - # without metadata: 0
           - # with DCP color calibration (raw images only): 0
           - # with LCP lens distortion initialization: 0
           - # with LCP vignetting calibration: 0
           - # with LCP chromatic aberration correction models: 0
        - # Cameras Intrinsics: 2
[2024-06-15 09:05:55.657912] [0x00001270] [trace]   Embedded OCIO configuration file: 'C:\Program Files\Meshroom-2023.3.0\aliceVision/share/aliceVision/config.ocio' found.
Program called with the following parameters:
 * allowSingleView = 1
 * allowedCameraModels = "pinhole,radial1,radial3,brown,fisheye4,fisheye1,3deanamorphic4,3deradial4,3declassicld"
 * colorProfileDatabase = "" (default)
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLength = -1 (default)
 * defaultFocalRatio = 1 (default)
 * defaultOffsetX = 0 (default)
 * defaultOffsetY = 0 (default)
 * errorOnMissingColorProfile = 1 (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:\Users\User\AppData\Local\Temp\tmp3ua6mg5b/CameraInit/961e54591174ec5a2457c66da8eadc0cb03d89ba/viewpoints.sfm"
 * lensCorrectionProfileInfo = "${ALICEVISION_LENS_PROFILE_INFO}"
 * lensCorrectionProfileSearchIgnoreCameraModel = 1
 * maxCoresAvailable =  Unknown Type "unsigned int" (default)
 * maxMemoryAvailable = 18446744073709551615 (default)
 * output = "C:/Users/User/AppData/Local/Temp/tmp3ua6mg5b/CameraInit/961e54591174ec5a2457c66da8eadc0cb03d89ba/cameraInit.sfm"
 * rawColorInterpretation =  Unknown Type "enum aliceVision::image::ERawColorInterpretation"
 * sensorDatabase = "C:\Program Files\Meshroom-2023.3.0\aliceVision\share\aliceVision\cameraSensors.db"
 * verboseLevel = "info"
 * viewIdMethod =  Unknown Type "enum aliceVision::sfmDataIO::EViewIdMethod"
 * viewIdRegex = ".*?(\d+)" (default)

Hardware :
        Detected core count : 16
        OpenMP will use 16 cores
        Detected available memory : 25019 Mo

[09:05:55.849605][info] 0 profile(s) stored in the LCP database.
[09:05:56.025757][warning] Some image(s) have no serial number to identify the camera/lens device.
This makes it impossible to correctly group the images by device if you have used multiple identical (same model) camera devices.
The reconstruction will assume that only one device has been used, so if 2 images share the same focal length approximation they will share the same internal camera parameters.
10 image(s) are concerned.
[09:05:56.032006][info] CameraInit report:
        - # Views: 10
           - # with focal length initialization (from metadata): 10
           - # without metadata: 0
           - # with DCP color calibration (raw images only): 0
           - # with LCP lens distortion initialization: 0
           - # with LCP vignetting calibration: 0
           - # with LCP chromatic aberration correction models: 0
        - # Cameras Intrinsics: 1
Traceback (most recent call last):
  File "C:\Release\sources\Meshroom\meshroom\ui\graph.py", line 493, in execute
  File "C:\Release\sources\Meshroom\meshroom\core\taskManager.py", line 222, in compute
  File "C:\Release\sources\Meshroom\meshroom\core\node.py", line 934, in beginSequence
  File "C:\Release\sources\Meshroom\meshroom\core\node.py", line 354, in upgradeStatusTo
  File "C:\Release\sources\Meshroom\meshroom\core\node.py", line 339, in saveStatusFile
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/User/Documents/Work/SfM_PROJECTS/LAND_Salt_Lake_2024_06_09_OSGB/2024-06-09_Anafi03/Salt_lake_2024-06-09_OSGB_Meshroom/Salt_Lake_2024-06-09_OSGB_Meshroom01/MeshroomCache/CameraInit/ee97b191f1c0e9102310149b923451c862aef4c3/status.writing.b4ce8dd7-a558-4b20-8888-98efd5b9f032'

If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: Windows 11 pro
 - Python version (not sure)
 - Qt/PySide version (again not sure)
 - Meshroom version: 2023.3.0 - just downloaded the standard version - I certainly haven't 'built' anything
   - Binary version (if applicable) (not sure)
   - Commit reference (if applicable) (not sure)

You'll probably gather from the above information that I'm certainly not an advanced user, but I would very much like to be able to use the application again. As far as I am aware, the associated programs (windows visual C++ and Nvidia drivers etc.) are up to date)

Any suggestions for a solution would be gratefully received.

**Comment by fabiencastan** [comment]
That's strange. Storage full? Project path too long?..

**Comment by ChrisM2017** [comment]
Thanks for the direction, Fabian. I shortened the project path and everything worked again as normal. Thanks again for your time.

**Comment by fabiencastan** [comment]
[max length for command lines on windows](https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation)
