### ISSUE TITLE
Linux (no CUDA): PrepareDenseScene Errors

### ISSUE THREAD

**Issue by dddaniel** [alicevision/meshroom#400]
Hi,

I am trying to get meshroom running on my debian notebook without an nvidia card :(
I build from current develop branch with:

> -DCMAKE_BUILD_TYPE=Release
-DALICEVISION_BUILD_SFM=ON
-DALICEVISION_USE_CUDA=OFF
-DCMAKE_CXX_FLAGS="-fPIC -O2" 
-DCMAKE_C_FLAGS="-fPIC -O2"

But it fails when running at PrepareDenseScene:
```
[6/11] PrepareDenseScene
 - commandLine: aliceVision_prepareDenseScene  --outputFileType exr --verboseLevel info --saveMatricesTxtFiles False --saveMetadata True --input "/tmp/MeshroomCache/StructureFromMotion/122c60fd3a81df744b01fcbf7a4e69e006d974c1/sfm.abc" --output "/tmp/MeshroomCache/PrepareDenseScene/e2e3da3bbde8171b8d9374f9cef46ecfffeaf88a" --rangeStart 0 --rangeSize 17
 - logFile: /tmp/MeshroomCache/PrepareDenseScene/e2e3da3bbde8171b8d9374f9cef46ecfffeaf88a/0.log
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/daniel/srcs/meshroom/meshroom/core/stats.py", line 206, in run
    self.updateStats()
  File "/home/daniel/srcs/meshroom/meshroom/core/stats.py", line 200, in updateStats
    if self.chunk.statistics.update(self.proc):
  File "/home/daniel/srcs/meshroom/meshroom/core/stats.py", line 162, in update
    self.computer.update()
  File "/home/daniel/srcs/meshroom/meshroom/core/stats.py", line 52, in update
    self._addKV('ioCounters', psutil.disk_io_counters())
  File "/home/daniel/.local/lib/python2.7/site-packages/psutil/__init__.py", line 2026, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/home/daniel/.local/lib/python2.7/site-packages/psutil/_pslinux.py", line 1115, in disk_io_counters
    for entry in gen:
  File "/home/daniel/.local/lib/python2.7/site-packages/psutil/_pslinux.py", line 1088, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   8       0 sda 2335644 992883 127952412 690849 4449212 3774373 209685981 2280931 0 777700 2232688 0 0 0 0\n'

(' - elapsed time:', '0:00:00.487925')
[2019-02-17 11:27:55,880][ERROR] Error on node computation: Error on node "PrepareDenseScene_1(0)":
Log:
Program called with the following parameters:
 * input = "/tmp/MeshroomCache/StructureFromMotion/122c60fd3a81df744b01fcbf7a4e69e006d974c1/sfm.abc"
 * output = "/tmp/MeshroomCache/PrepareDenseScene/e2e3da3bbde8171b8d9374f9cef46ecfffeaf88a"
 * outputFileType = "exr"
 * rangeSize = 17
 * rangeStart = 0
 * saveMatricesTxtFiles = 0
 * saveMetadata = 1
 * verboseLevel = "info"

[11:27:55.866749][error] Unknown input SfM data format: '.abc'
[11:27:55.866820][error] The input SfMData file '/tmp/MeshroomCache/StructureFromMotion/122c60fd3a81df744b01fcbf7a4e69e006d974c1/sfm.abc' cannot be read.
```

I found more issues like that in the history, but none with that line:
`ValueError: not sure how to interpret line '   8       0 sda 2335644 992883 127952412 690849 4449212 3774373 209685981 2280931 0 777700 2232688 0 0 0 0\n'`

Full log:
[meshroom.log](https://github.com/alicevision/meshroom/files/2872855/meshroom.log)

**Comment by fabiencastan** [comment]
You need to build with (Alembic)[https://github.com/alembic/alembic].
Add `-DALICEVISION_USE_ALEMBIC=ON` to be sure to build with the Alembic support.

**Comment by dddaniel** [comment]
> You need to build with [Alembic](https://github.com/alembic/alembic).
> Add `-DALICEVISION_USE_ALEMBIC=ON` to be sure to build with the Alembic support.

Thanks, that got me one error further :)
I am running now into:
`aliceVision_depthMapEstimation not found`
Because I build without CUDA.

Is there a way to run meshroom without CUDA ?
From looking at the command chain in the UI, it seems there is no way to reconstruct 3D meshes without the depthMapEstimation.

**Comment by dddaniel** [comment]
Also these stacktraces and errors are still printed for every module:
```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/daniel/srcs/meshroom/meshroom/core/stats.py", line 206, in run
    self.updateStats()
  File "/home/daniel/srcs/meshroom/meshroom/core/stats.py", line 200, in updateStats
    if self.chunk.statistics.update(self.proc):
  File "/home/daniel/srcs/meshroom/meshroom/core/stats.py", line 162, in update
    self.computer.update()
  File "/home/daniel/srcs/meshroom/meshroom/core/stats.py", line 52, in update
    self._addKV('ioCounters', psutil.disk_io_counters())
  File "/home/daniel/.local/lib/python2.7/site-packages/psutil/__init__.py", line 2026, in disk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/home/daniel/.local/lib/python2.7/site-packages/psutil/_pslinux.py", line 1115, in disk_io_counters
    for entry in gen:
  File "/home/daniel/.local/lib/python2.7/site-packages/psutil/_pslinux.py", line 1088, in read_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   8       0 sda 2749347 1097941 147829313 806477 4812971 4058859 226737660 2430652 0 866900 2440332 0 0 0 0\n'
```

**Comment by fabiencastan** [comment]
You can connect the Meshing node directly on the StructureFromMotion node.
You will need the PrepareDenseScene in input of the Texturing.

**Comment by dddaniel** [comment]
> You can connect the Meshing node directly on the StructureFromMotion node.
> You will need the PrepareDenseScene in input of the Texturing.

I did, now the texturing is failing:
```
[2019-02-18 14:12:53,987][ERROR] Error on node computation: Error on node "Texturing_1":
Log:
Program called with the following parameters:
 * angleHardThreshold = 90
 * bestScoreThreshold = 0
 * downscale =  Unknown Type "j"
 * fillHoles = 0
 * flipNormals = 0
 * forceVisibleByAllVertices = 0
 * imagesFolder = ""
 * input = "/tmp/MeshroomCache/PrepareDenseScene/5d00baabdf3dc28ae557fd751748337791693232"
 * inputDenseReconstruction = "/tmp/MeshroomCache/Meshing/6ebf4cc89484e622c0d59d128652f194c50293ca/denseReconstruction.bin"
 * inputMesh = "/tmp/MeshroomCache/MeshFiltering/b42f519c727441847337333c05500f73ef40df81/mesh.obj"
 * maxNbImagesForFusion = 3
 * output = "/tmp/MeshroomCache/Texturing/82aee05d79269276afb4da06ab6af176df388ab6"
 * outputTextureFileType = "png"
 * padding =  Unknown Type "j"
 * textureSide =  Unknown Type "j"
 * unwrapMethod = "Basic"
 * verboseLevel = "info"
 * visibilityRemappingMethod = "PullPush"

[14:12:53.975016][error] The input SfMData file '/tmp/MeshroomCache/PrepareDenseScene/5d00baabdf3dc28ae557fd751748337791693232' cannot be read.

[2019-02-18 14:12:53,987][ERROR] Error during Graph execution Error on node "Texturing_1":
Log:
Program called with the following parameters:
 * angleHardThreshold = 90
 * bestScoreThreshold = 0
 * downscale =  Unknown Type "j"
 * fillHoles = 0
 * flipNormals = 0
 * forceVisibleByAllVertices = 0
 * imagesFolder = ""
 * input = "/tmp/MeshroomCache/PrepareDenseScene/5d00baabdf3dc28ae557fd751748337791693232"
 * inputDenseReconstruction = "/tmp/MeshroomCache/Meshing/6ebf4cc89484e622c0d59d128652f194c50293ca/denseReconstruction.bin"
 * inputMesh = "/tmp/MeshroomCache/MeshFiltering/b42f519c727441847337333c05500f73ef40df81/mesh.obj"
 * maxNbImagesForFusion = 3
 * output = "/tmp/MeshroomCache/Texturing/82aee05d79269276afb4da06ab6af176df388ab6"
 * outputTextureFileType = "png"
 * padding =  Unknown Type "j"
 * textureSide =  Unknown Type "j"
 * unwrapMethod = "Basic"
 * verboseLevel = "info"
 * visibilityRemappingMethod = "PullPush"

[14:12:53.975016][error] The input SfMData file '/tmp/MeshroomCache/PrepareDenseScene/5d00baabdf3dc28ae557fd751748337791693232' cannot be read.
```

![nodes-screenshot](https://user-images.githubusercontent.com/7884843/52953784-c11d4300-3388-11e9-8e55-88798af0053b.png)

**Comment by vsandre** [comment]
See https://github.com/alicevision/meshroom/wiki/Draft-Meshing

**Comment by ArizonaOkie** [comment]
So whats the final decision.  Meshroom will not work without CUDA.  I followed the node setup and continue to get errors.  Please someone that has completed a project using AMD Graphics step in and give us some tips and advice.
