### ISSUE TITLE
Using Meshroom to generate "texturedMesh.obj" but failed. (AliceVision is successfully installed under Ubuntu 16.04 and works well.)

### ISSUE THREAD

**Issue by zengletian1491** [alicevision/meshroom#679]
**My input command lines**
export PYTHONPATH=$PYTHONPATH:/home/zeng/Work/meshroom
python ./meshroom_photogrammetry --input /home/zeng/Work/data/dataset_buddha/buddha_mini6 --output /home/zeng/Work/data/dataset_buddha/buddha_mini6

**Describe the bug**
[2019-10-14 17:10:36,584][WARNING] == The following plugins could not be loaded ==
  * simpleFarmSubmitter: No module named simpleFarm

Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "PINHOLE_CAMERA" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = 0.92261 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "20EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "/tmp/tmpcnYcim/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm"
 * output = "/tmp/tmpcnYcim/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm"
 * sensorDatabase = ""
 * verboseLevel = "info"

terminate called after throwing an instance of 'std::out_of_range'
  what():  PINHOLE_CAMERA
Aborted (core dumped)
Traceback (most recent call last):
  File "./meshroom_photogrammetry", line 126, in <module>
    views, intrinsics = cameraInit.nodeDesc.buildIntrinsics(cameraInit, images)
  File "/home/zeng/Work/meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 192, in buildIntrinsics
    subprocess.returncode, cmd)
RuntimeError: CameraInit failed with error code 134. Command was: "aliceVision_cameraInit  --groupCameraFallback folder --defaultFieldOfView 45.0 --verboseLevel info --sensorDatabase "" --output "/tmp/tmpcnYcim/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm" --allowSingleView 1  --input "/tmp/tmpcnYcim/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm""

**Comment by zengletian1491** [comment]
Solution:
1、 install the AliceVision once more(maybe you should download a new version of AliceVision on the github);
2、install the meshroom once more(maybe you should download a new version of Meshroom on the github).

**Comment by zengletian1491** [comment]
After doing this, Meshroom is back to normal！
