### ISSUE TITLE
[bug] RuntimeError: Error on node "Meshing_1"

### ISSUE THREAD

**Issue by stasbar** [alicevision/meshroom#762]
**Describe the bug**
For [this set of photos](https://photos.app.goo.gl/4fpk2hbGuANhez1d9) it works fine. (108 photos each 8MB)
But for [this](https://photos.app.goo.gl/mVrDWMzxKgDTmr5UA) it fails with the following error. (191 photos each 8MB)

**To Reproduce**
```
./meshroom_photogrammetry --cache ~/MeshroomCacheDes07 --input ~/DemMorenaPixel/ --output ~/Out_DemMorenaPixel
```

**Log**

```
...
[19:20:01.532521][info] Create visibilities (62/190)
[19:20:02.373776][info] Create visibilities (63/190)
[19:20:03.075582][info] Visibilities created.
[19:20:03.079198][info] Compute max angle per point
[19:20:03.079209][info] angleFactor: 15
[19:20:06.345207][info] 400677 invalid points removed.
[19:20:06.983611][info] Filter by angle score and sim score
[19:20:06.983640][info] Build nanoflann KdTree index.
[19:20:08.639105][info] KdTree created for 7068817 points.
[19:20:09.303758][info] Filtering done.
[19:20:09.620360][info] 2896019 invalid points removed.
[19:20:09.850709][info] The number of points is below the max number of vertices.
[19:20:09.850740][info] 3D points loaded and filtered to 4172798 points (maxVertices is 5000000).
[19:20:09.850746][info] Create final visibilities
[19:20:10.755383][info] NANOFLANN: KdTree created.
[19:20:10.763677][info] Create visibilities (0/190)
[19:20:10.763702][info] Create visibilities (127/190)
[19:20:10.763717][info] Create visibilities (64/190)
...
[19:21:59.743710][info] Create visibilities (62/190)
[19:22:00.382480][info] Create visibilities (63/190)
[19:22:01.044536][info] Visibilities created.
[19:22:01.046813][info] fuseFromDepthMaps done: 4172798 points created.
[19:22:19.617412][info] 27095359 cells created by tetrahedralization.
[19:22:51.814679][info] coutInvalidVertices: 0
[19:22:51.814718][info] neighboringCellsPerVertexTmp: 4174129
[19:22:51.843078][info] verticesCoords: 4174129
[19:23:06.381526][info] Histogram of number of cams per point:
[19:23:06.381560][info]     0: 1331
[19:23:06.381581][info]     1: 0
[19:23:06.381585][info]     2: 168314
[19:23:06.381589][info]     3: 355577
[19:23:06.381593][info]     4: 445368
[19:23:06.381596][info]     5: 468705
[19:23:06.381600][info]     6: 461794
...
[19:23:14.259485][info]     529: 0
[19:23:14.259489][info]     530: 1
[19:23:18.243835][info] DelaunayGraphCut::reconstructExpetiments
[19:23:18.243873][info] fixesSigma: false
[19:23:18.243883][info] sigma: 4
[19:23:18.243898][info] Jancosek IJCV method ( delta*100 = 10 ):
[19:23:18.243902][info] Computing s-t graph weights.
[19:23:18.259995][info] setIsOnSurface nbSurfaceFacets: 0
[19:25:49.867962][info] Forcing t-edges
[19:27:07.159022][info] reconstructGC start.
[19:27:07.159062][info] Maxflow: start allocation.
[19:27:08.026908][info] Maxflow: add nodes.
[19:27:11.235413][info] Maxflow: add edges.
Killed

WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Publish_1" from Status.SUBMITTED to Status.NONE
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/opt/Meshroom/setupInitScriptUnix.py", line 39, in run
  File "bin/meshroom_photogrammetry", line 144, in <module>
  File "/opt/Meshroom/meshroom/core/graph.py", line 1131, in executeGraph
  File "/opt/Meshroom/meshroom/core/node.py", line 274, in process
  File "/opt/Meshroom/meshroom/core/desc.py", line 453, in processChunk
RuntimeError: Error on node "Meshing_1":
Log:
Program called with the following parameters:
 * addLandmarksToTheDensePointCloud = 0
 * angleFactor = 15
 * colorizeOutput = 0
 * contributeMarginFactor = 2
 * depthMapsFilterFolder = "/macierz/home/s160518/MeshroomCacheDes02/DepthMapFilter/a4f298481f423d4e41c712a36258f57c5fabe666"
 * depthMapsFolder = "/macierz/home/s160518/MeshroomCacheDes02/DepthMap/f714b011be4658118e75086b9cd3c7b7966af823"
 * estimateSpaceFromSfM = 1
 * estimateSpaceMinObservationAngle = 10
 * estimateSpaceMinObservations = 3
 * input = "/macierz/home/s160518/MeshroomCacheDes02/StructureFromMotion/57dc82b565a93f548e64363f719ffba61dd4f1e4/sfm.abc"
 * maxInputPoints = 50000000
 * maxPoints = 5000000
 * maxPointsPerVoxel = 1000000
 * minAngleThreshold = 1
 * minStep = 2
 * output = "/macierz/home/s160518/MeshroomCacheDes02/Meshing/e2f35e281db67be7cb65e055cfbdbc793a315cbf/densePointCloud.abc"
 * outputMesh = "/macierz/home/s160518/MeshroomCacheDes02/Meshing/e2f35e281db67be7cb65e055cfbdbc793a315cbf/mesh.obj"
 * partitioning =  Unknown Type "17EPartitioningMode"
 * pixSizeMarginFinalCoef = 4
 * pixSizeMarginInitCoef = 2
 * refineFuse = 1
 * repartition =  Unknown Type "16ERepartitionMode"
 * saveRawDensePointCloud = 0
 * simFactor = 15
 * simGaussianSize = 10
 * simGaussianSizeInit = 10
 * universePercentile = 0.999 (default)
 * verboseLevel = "info"
 * voteMarginFactor = 4

[19:16:18.238521][info] Found 1 image dimension(s):
[19:16:18.238631][info]         - [4032x3024]
[19:16:18.506061][info] Overall maximum dimension: [4032x3024]
[19:16:18.506115][warning] repartitionMode: 1
[19:16:18.506121][warning] partitioningMode: 1
[19:16:18.506125][info] Meshing mode: multi-resolution, partitioning: single block.
[19:16:18.506131][info] Estimate space from SfM.
[19:16:18.578780][info] Estimate space done.
[19:16:18.578802][info] pointToJoinPixSizeDist: 2
[19:16:18.699533][info] Estimated: 4 4 2
[19:16:18.699572][info] voxelNeighs.size(): 32
[19:16:18.959830][info] Creating dense point cloud.
[19:16:18.959849][info] fuseFromDepthMaps, maxVertices: 5000000
[19:16:19.606560][info] simFactor: 15
[19:16:19.606605][info] nbPixels: 2316625920
[19:16:19.606637][info] maxVertices: 5000000
[19:16:19.606641][info] step: 6
[19:16:19.606644][info] realMaxVertices: 64350720
[19:16:19.606647][info] Load depth maps and add points.
[19:17:50.228137][info] Filter initial 3D points by pixel size to remove duplicates.
[19:17:50.228180][info] Build nanoflann KdTree index.
[19:18:05.099482][info] KdTree created for 64350720 points.
[19:18:06.381574][info] Filtering done.
[19:18:06.629738][info] 56881226 invalid points removed.
[19:18:06.682256][info] 3D points loaded and filtered to 7469494 points.
[19:18:06.682279][info] Init visibilities to compute angle scores
[19:18:08.645518][info] NANOFLANN: KdTree created.
[19:18:08.666040][info] Create visibilities (64/190)
[19:18:08.666035][info] Create visibilities (0/190)
[19:18:08.666042][info] Create visibilities (127/190)
...
[19:20:01.532521][info] Create visibilities (62/190)
[19:20:02.373776][info] Create visibilities (63/190)
[19:20:03.075582][info] Visibilities created.
[19:20:03.079198][info] Compute max angle per point
[19:20:03.079209][info] angleFactor: 15
[19:20:06.345207][info] 400677 invalid points removed.
[19:20:06.983611][info] Filter by angle score and sim score
[19:20:06.983640][info] Build nanoflann KdTree index.
[19:20:08.639105][info] KdTree created for 7068817 points.
[19:20:09.303758][info] Filtering done.
[19:20:09.620360][info] 2896019 invalid points removed.
[19:20:09.850709][info] The number of points is below the max number of vertices.
[19:20:09.850740][info] 3D points loaded and filtered to 4172798 points (maxVertices is 5000000).
[19:20:09.850746][info] Create final visibilities
[19:20:10.755383][info] NANOFLANN: KdTree created.
[19:20:10.763677][info] Create visibilities (0/190)
[19:20:10.763702][info] Create visibilities (127/190)
...
[19:21:59.743710][info] Create visibilities (62/190)
[19:22:00.382480][info] Create visibilities (63/190)
[19:22:01.044536][info] Visibilities created.
[19:22:01.046813][info] fuseFromDepthMaps done: 4172798 points created.
[19:22:19.617412][info] 27095359 cells created by tetrahedralization.
[19:22:51.814679][info] coutInvalidVertices: 0
[19:22:51.814718][info] neighboringCellsPerVertexTmp: 4174129
[19:22:51.843078][info] verticesCoords: 4174129
[19:23:06.381526][info] Histogram of number of cams per point:
[19:23:06.381560][info]     0: 1331
[19:23:06.381581][info]     1: 0
[19:23:06.381585][info]     2: 168314
[19:23:06.381589][info]     3: 355577
...
[19:23:14.259485][info]     529: 0
[19:23:14.259489][info]     530: 1
[19:23:18.243835][info] DelaunayGraphCut::reconstructExpetiments
[19:23:18.243873][info] fixesSigma: false
[19:23:18.243883][info] sigma: 4
[19:23:18.243898][info] Jancosek IJCV method ( delta*100 = 10 ):
[19:23:18.243902][info] Computing s-t graph weights.
[19:23:18.259995][info] setIsOnSurface nbSurfaceFacets: 0
[19:25:49.867962][info] Forcing t-edges
[19:27:07.159022][info] reconstructGC start.
[19:27:07.159062][info] Maxflow: start allocation.
[19:27:08.026908][info] Maxflow: add nodes.
[19:27:11.235413][info] Maxflow: add edges.
Killed
```

**Desktop (please complete the following and other pertinent information):**
 - OS: Linux 5.0.0-37-generic #40~18.04.1-Ubuntu SMP
 - Python version: Python 2.7.17
 - Qt/PySide version not sure how to get it
 - Meshroom version: Meshroom-2019.2.0
   - Binary version (if applicable) 2019.2.0

**Comment by sanzoghenzo** [comment]
Same here, running 2019.2.0 on ElementaryOS (5.3.0-28-generic #30~18.04.1-Ubuntu SMP), 281 photos.

I tried on windows with 260 photos (207 valid photos), and the log reported an abnormal termination for exausted memory. Changing the maxPoints to 1M did the trick.

Still need to verify if the linux version runs with fewer maxPoints, though.
