### ISSUE TITLE
[bug] Windows binary crashes on startup - ModuleNotFoundError: No module named 'PySide2.QtCore'

### ISSUE THREAD

**Issue by EnragedViper** [alicevision/meshroom#852]
**Describe the bug**
Running the Meshroom binary on Windows 10 crashes on startup with the following error:
```
E:\EnragedViper\Downloads\Meshroom-2019.2.0>meshroom
Traceback (most recent call last):
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\venv\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\venv\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "meshroom/ui/__main__.py", line 10, in <module>
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\meshroom\ui\app.py", line 5, in <module>
ModuleNotFoundError: No module named 'PySide2.QtCore'
```

**To Reproduce**
1. Dowload the Meshroom binary from https://alicevision.org/#meshroom, which as of this issue is version 2019.2.0
2. Extract and run Meshroom via the command line (as it closes immediately due to crashing on startup otherwise)
3. See error

**Expected behavior**
It should run without crashing.

**Screenshots**
Not applicable.

**Log**
Not applicable.

**Desktop (please complete the following and other pertinent information):**
 - OS: Windows 10
 - Python version 3.7.7
 - PySide version 5.14.2
 - Meshroom binary version 2019.2.0

**Additional context**
I expected a system-wide installation of Python to be unnecessary as I thought Python was packaged with the binary. Regardless, with Python 3.7.7, running `pip install PySide2` (to install as of writing version 5.14.2) and re-running Meshroom still produces the same error. I note also running Python in interactive mode and running `import PySide.QtCore` also produces the same error.

**Comment by tanant** [comment]
I think I've got the same setup here as you and am not hitting this error, I've got both python 2.7 and 3.8 installed - neither with any access to QT libraries - and have just tried it in both powershell and regular old command prompt, and have had no errors.

I've tried poking around a little in the python side of things, but nothing obvious comes to mind that i can see in my local env that'd be all that special - anything I can dump here that'd help?

**Comment by EnragedViper** [comment]
It’s very unusual, I had time to try to debug it a bit today and it seems to be loading the Python dll included, but it still crashes with the same error in either CMD or PowerShell.

I was considering installing the QT libraries, but they seem unnecessary, because I managed to run Meshroom successfully on another Windows 10 computer (with only Python 3.7.2 installed, but even then I would assume that would be unnecessary as well), but unfortunately, I can’t use it there, because it doesn’t have a CUDA-supported graphics card.
 
> anything I can dump here that'd help?

That’s kind of you to offer, but unfortunately, I'm not sure what the problem is exactly (although it seems to be to do with Python). If there’s any further way I could debug it and maybe figure out what the problem is, let me know.

As a last resort the command line based `meshroom_photogrammetry.exe` seems to work for the time being, but it would be better if I could get the GUI to work.

**Comment by natowi** [comment]
The only thing that comes to mind is a possible conflict between the different python versions and qt.
But with Windows the issue could be basically anything you would not think of.
