### ISSUE TITLE
"The system cannot find the path specified" error when running CameraInit

### ISSUE THREAD

**Issue by JanWalterSluka** [alicevision/meshroom#879]
I was using Meshroom on Windows 10 without problems last year, however now when I try to run CameraInit I get the error pasted below in the command line. I tried to redownload everything and reinstall Python, but that did not help. I also tried using 2018.1 instead of 2019.2 without any luck. Setting path to alicevision did not help either (although AFAIK that shouldn't even be necessary for running on Windows). I can't figure out what is wrong, please help.
```
ERROR:root:Error during Graph execution Error on node "CameraInit_1":
Log:
The system cannot find the path specified.
Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "E:/MeshroomCache/CameraInit/3a576419934bcf086baf0845f2777df5acd1121b//viewpoints.sfm"
 * output = "E:/MeshroomCache/CameraInit/3a576419934bcf086baf0845f2777df5acd1121b/cameraInit.sfm"
 * sensorDatabase = "D:/Program Files/Meshroom-2019.2.0/aliceVision/share/aliceVision/cameraSensors.db"
 * verboseLevel = "info"

[21:51:05.417588][info] CameraInit report:
        - # views listed: 30
           - # views with an initialized intrinsic listed: 30
           - # views without metadata (with a default intrinsic): 0
        - # intrinsics listed: 1
```

**Comment by natowi** [comment]
"The system cannot find the path specified."

There is something wrong with your image and/or installation path

**Comment by NexTechAR-Scott** [comment]
Is this a new install of MR and a new project from scratch?

If it's a moved / copied project update your camera.db and octree paths

**Comment by JanWalterSluka** [comment]
I get the error even when trying it in a new project. Meshroom is a fresh installation.

**Comment by NexTechAR-Scott** [comment]
> I get the error even when trying it in a new project. Meshroom is a fresh installation.

So you are not starting a new project from an older project.mg.

Fresh install of Meshroom, File->New->drag / import images

Are you saving the project.mg before hitting start?

If yes try without and let Meshroom cache get created inside root of app path which appears to be D:\\ and your inages are in E:\\ which there is nothing wrong with.

The only thing that makes sense off the top of my head is a permissions issue.

**Comment by hhiraba** [comment]
I have a similar problem on Ubuntu 18.04 with the latest release.

I ran `meshroom_photography` and got error as below.
```
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/opt/Meshroom/setupInitScriptUnix.py", line 39, in run
  File "bin/meshroom_photogrammetry", line 144, in <module>
  File "/opt/Meshroom/meshroom/core/graph.py", line 1131, in executeGraph
  File "/opt/Meshroom/meshroom/core/node.py", line 274, in process
  File "/opt/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 238, in processChunk
  File "/opt/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 228, in createViewpointsFile
FileNotFoundError: [Errno 2] No such file or directory: './cache//CameraInit/a3e6518fbcbb9d546afde63373d020fd5d87e4e5//viewpoints.sfm'
```

I found that the cache directory is created dually if `--cache` option is passed.
Although I don't know very much how meshroom works, `tmpCache` and `node.internalFolder` in [CameraInit.py](https://github.com/alicevision/meshroom/blob/6b99e0b2c28453afc3b936f316a37c0d317264ea/meshroom/nodes/aliceVision/CameraInit.py#L260) probably become the same value.

(my attempts. sorry for too long)
```console
hhiraba:~/meshroom$ ./Meshroom-2019.2.0/meshroom_photogrammetry --input ./test_images/ --output ./output --cache cache_#879
Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportColoredPointCloud, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, LDRToHDR, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "20EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "/tmp/tmpl7gme8_m/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm"
 * output = "/tmp/tmpl7gme8_m/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm"
 * sensorDatabase = "/mnt/c/Users/hhiraba/prog/meshroom/Meshroom-2019.2.0/aliceVision/share/aliceVision/cameraSensors.db"
 * verboseLevel = "info"

[23:31:05.471716][warning] Image '00000000.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[23:31:05.479063][warning] Some image(s) have no serial number to identify the camera/lens device.
This makes it impossible to correctly group the images by device if you have used multiple identical (same model) camera devices.
The reconstruction will assume that only one device has been used, so if 2 images share the same focal length approximation they will share the same internal camera parameters.
1 image(s) are concerned.
[23:31:05.479724][info] CameraInit report:
        - # views listed: 1
           - # views with an initialized intrinsic listed: 1
           - # views without metadata (with a default intrinsic): 1
        - # intrinsics listed: 1
Nodes to execute:  ['CameraInit_1', 'FeatureExtraction_1', 'ImageMatching_1', 'FeatureMatching_1', 'StructureFromMotion_1', 'PrepareDenseScene_1', 'DepthMap_1', 'DepthMapFilter_1', 'Meshing_1', 'MeshFiltering_1', 'Texturing_1', 'Publish_1']

[1/12] CameraInit
 - elapsed time: 0:00:00.051923
ERROR:root:Error on node computation: [Errno 2] No such file or directory: 'cache_#879/CameraInit/1c4e79410b4d9ce85e1e13136262525a1d12a65f//viewpoints.sfm'
WARNING: downgrade status on node "FeatureExtraction_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "ImageMatching_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureMatching_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "StructureFromMotion_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "PrepareDenseScene_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Publish_1" from Status.SUBMITTED to Status.NONE
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/opt/Meshroom/setupInitScriptUnix.py", line 39, in run
  File "bin/meshroom_photogrammetry", line 144, in <module>
  File "/opt/Meshroom/meshroom/core/graph.py", line 1131, in executeGraph
  File "/opt/Meshroom/meshroom/core/node.py", line 274, in process
  File "/opt/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 238, in processChunk
  File "/opt/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 228, in createViewpointsFile
FileNotFoundError: [Errno 2] No such file or directory: 'cache_#879/CameraInit/1c4e79410b4d9ce85e1e13136262525a1d12a65f//viewpoints.sfm'
hhiraba:~/meshroom$ ls ./cache_#879/  # !!!! cache_#879 dirctory was dually created !!!!
cache_#879
hhiraba:~/meshroom$ ls ./cache_#879/cache_#879/
CameraInit  DepthMapFilter     FeatureMatching  MeshFiltering  PrepareDenseScene  StructureFromMotion
DepthMap    FeatureExtraction  ImageMatching    Meshing        Publish            Texturing
hhiraba:~/meshroom$ ./Meshroom-2019.2.0/meshroom_photogrammetry --input ./test_images/ --output ./output --cache cache_#879_nested/child
Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportColoredPointCloud, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, LDRToHDR, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "20EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "/tmp/tmp8ehyitf0/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm"
 * output = "/tmp/tmp8ehyitf0/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm"
 * sensorDatabase = "/mnt/c/Users/hhiraba/prog/meshroom/Meshroom-2019.2.0/aliceVision/share/aliceVision/cameraSensors.db"
 * verboseLevel = "info"

[23:32:47.639440][warning] Image '00000000.jpg' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

[23:32:47.646766][warning] Some image(s) have no serial number to identify the camera/lens device.
This makes it impossible to correctly group the images by device if you have used multiple identical (same model) camera devices.
The reconstruction will assume that only one device has been used, so if 2 images share the same focal length approximation they will share the same internal camera parameters.
1 image(s) are concerned.
[23:32:47.647514][info] CameraInit report:
        - # views listed: 1
           - # views with an initialized intrinsic listed: 1
           - # views without metadata (with a default intrinsic): 1
        - # intrinsics listed: 1
Nodes to execute:  ['CameraInit_1', 'FeatureExtraction_1', 'ImageMatching_1', 'FeatureMatching_1', 'StructureFromMotion_1', 'PrepareDenseScene_1', 'DepthMap_1', 'DepthMapFilter_1', 'Meshing_1', 'MeshFiltering_1', 'Texturing_1', 'Publish_1']

[1/12] CameraInit
 - elapsed time: 0:00:00.052017
ERROR:root:Error on node computation: [Errno 2] No such file or directory: 'cache_#879_nested/child/CameraInit/1c4e79410b4d9ce85e1e13136262525a1d12a65f//viewpoints.sfm'
WARNING: downgrade status on node "FeatureExtraction_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "ImageMatching_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureMatching_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "StructureFromMotion_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "PrepareDenseScene_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Publish_1" from Status.SUBMITTED to Status.NONE
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/opt/Meshroom/setupInitScriptUnix.py", line 39, in run
  File "bin/meshroom_photogrammetry", line 144, in <module>
  File "/opt/Meshroom/meshroom/core/graph.py", line 1131, in executeGraph
  File "/opt/Meshroom/meshroom/core/node.py", line 274, in process
  File "/opt/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 238, in processChunk
  File "/opt/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 228, in createViewpointsFile
FileNotFoundError: [Errno 2] No such file or directory: 'cache_#879_nested/child/CameraInit/1c4e79410b4d9ce85e1e13136262525a1d12a65f//viewpoints.sfm'
hhiraba:~/meshroom$ ls cache_#879_nested/
child
hhiraba:~/meshroom$ ls cache_#879_nested/child/
cache_#879_nested
hhiraba:~/meshroom$ ls cache_#879_nested/child/cache_#879_nested/
child
hhiraba:~/meshroom$ ls cache_#879_nested/child/cache_#879_nested/child/
CameraInit  DepthMapFilter     FeatureMatching  MeshFiltering  PrepareDenseScene  StructureFromMotion
DepthMap    FeatureExtraction  ImageMatching    Meshing        Publish            Texturing
```

**Comment by NexTechAR-Scott** [comment]
If you run MeshRoom without saving the project first it creates a cache directory on it's own and that may be a location that does not have correct permissions.

The very first thing after launching MeshRoom should be to save the project to a folder that you choose.   

Don't run a project without saving it first.

**Comment by hhiraba** [comment]
My problem also occurred on Windows, and solved by passing an absolute path to the `--cache` option instead of a relative path.
But anyway, I will save project files at first from now on.
Thanks.

**Comment by natowi** [comment]
Is this issue solved now?
