### ISSUE TITLE
Open Recent is broken on Windows (wrong path separator?)

### ISSUE THREAD

**Issue by julianrendell** [alicevision/meshroom#912]
File menu -> Open Recent -> entries are listed as eg `/D:/Meshroom_Dev/test-project/mostree.mg`

Clicking on an entry results in:

```
[2020-05-23 16:12:48,660][ERROR] Traceback (most recent call last):
  File "D:\Meshroom_Src\meshroom\meshroom\ui\reconstruction.py", line 432, in load
    super(Reconstruction, self).load(filepath, setupProjectFile)
  File "D:\Meshroom_Src\meshroom\meshroom\ui\graph.py", line 314, in load
    g.load(filepath, setupProjectFile)
  File "D:\Meshroom_Src\meshroom\meshroom\core\graph.py", line 247, in load
    with open(filepath) as jsonFile:
OSError: [Errno 22] Invalid argument: '/D:/Meshroom_Dev/test-project/mostree.mg'
```

Path should be `D:\Meshroom_Dev\test-project\mostree.mg`.

Exception dialog can be closed, and the program is still usable; can manually open the project using file->open.

**Comment by skinkie** [comment]
https://stackoverflow.com/questions/2953834/windows-path-in-python
