### ISSUE TITLE
compatibility issue detected [bug]

### ISSUE THREAD

**Issue by raphael2692** [alicevision/meshroom#961]
System Spec:

I'm running multiple reconstruction test with the same acquisition setup using the same .mg file via command line. Suddently I'm unable to use 'meshroom_compute myconf.mg' with this error:

```terminal
WARNING:root:Compatibility issue detected for node 'SfMTransform_1': DescriptionConflict
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/opt/Meshroom/setupInitScriptUnix.py", line 39, in run
  File "bin/meshroom_compute", line 64, in <module>
  File "/opt/Meshroom/meshroom/core/graph.py", line 1100, in executeGraph
  File "/opt/Meshroom/meshroom/core/graph.py", line 737, in dfsToProcess
  File "/opt/Meshroom/meshroom/core/graph.py", line 647, in dfs
  File "/opt/Meshroom/meshroom/core/graph.py", line 653, in dfsVisit
  File "/opt/Meshroom/meshroom/core/graph.py", line 659, in _dfsVisit
  File "/opt/Meshroom/meshroom/core/graph.py", line 714, in discoverVertex
RuntimeError: Can't compute node 'Meshing_1'WARNING:root:Compatibility issue detected for node 'SfMTransform_1': DescriptionConflict
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/opt/Meshroom/setupInitScriptUnix.py", line 39, in run
  File "bin/meshroom_compute", line 64, in <module>
  File "/opt/Meshroom/meshroom/core/graph.py", line 1100, in executeGraph
  File "/opt/Meshroom/meshroom/core/graph.py", line 737, in dfsToProcess
  File "/opt/Meshroom/meshroom/core/graph.py", line 647, in dfs
  File "/opt/Meshroom/meshroom/core/graph.py", line 653, in dfsVisit
  File "/opt/Meshroom/meshroom/core/graph.py", line 659, in _dfsVisit
  File "/opt/Meshroom/meshroom/core/graph.py", line 714, in discoverVertex
RuntimeError: Can't compute node 'Meshing_1'
```
Opening the .mg file with meshroom GUI this pop-up shows up:

![Annotazione 2020-06-22 215832](https://user-images.githubusercontent.com/24436489/85330663-1c0eff00-b4d5-11ea-9963-60673abf826a.jpg)

I tried to clean Meshroom cache at /temp and the cache folder I specified in the file. I also tried rebooting the system but the error keep occurring.

CentOS 7 x64
Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz
2x Tesla v4
192GB DDR4
SSD
Meshroom 2019.2 stable

**Comment by ChemicalXandco** [comment]
could you supply the `.mg` file?

**Comment by NexTechAR-Scott** [comment]
I think the answer is yes but just to make sure, you created the xxxx.mg on the same PC that you are currently having the issue on?

I only see warnings like that if I'm moving a graphfile from Win10 to Linux.

**Comment by raphael2692** [comment]
I solved the issue. The problem was a bad value (not properly coded string) on one of the keys of the sfmTransform node. I was editing the file on a ssh visual code studio ssh session. Thanks all for the suggestions!
