### ISSUE TITLE
[bug] Crash with Structure From Motion statistics

### ISSUE THREAD

**Issue by skinkie** [alicevision/meshroom#986]
**Describe the bug**
I am able to crash the application when toggling the Structure From Motion statistics. The interaction with the entire plugin should be investigated, because also other functions of this plugin do not behave as they should.

**To Reproduce**
1. Go to Image Viewer 
2. Click on Structure from Motion statistics (to enable)
3. Click on Structure from Motion statistics (to disable)
4. See error:

```
Thread 1 "python3.7" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e5869c in free () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7e5869c in free () at /lib64/libc.so.6
#1  0x00007fff6aa92930 in aliceVision::camera::IntrinsicBase::project(aliceVision::geometry::Pose3 const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, bool) const [clone .constprop.0] () at /opt/alicevision/lib64/libaliceVision_sfm.so.2
#2  0x00007fff6aa9557b in aliceVision::sfm::computeResidualsHistogram(aliceVision::sfmData::SfMData const&, aliceVision::BoxStats<double>&, aliceVision::Histogram<double>*, std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned int> > const&) () at /opt/alicevision/lib64/libaliceVision_sfm.so.2
#3  0x00007fff6ac5d3de in qtAliceVision::MViewStats::computeViewStats() () at /opt/alicevision/qml/AliceVision/libqtAliceVisionPlugin.so.0.1
#4  0x00007fff6ac3a134 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (qtAliceVision::MViewStats::*)()>::call(void (qtAliceVision::MViewStats::*)(), qtAliceVision::MViewStats*, void**) ()
    at /opt/alicevision/qml/AliceVision/libqtAliceVisionPlugin.so.0.1
#5  0x00007fff6ac381a2 in void QtPrivate::FunctionPointer<void (qtAliceVision::MViewStats::*)()>::call<QtPrivate::List<>, void>(void (qtAliceVision::MViewStats::*)(), qtAliceVision::MViewStats*, void**) ()
    at /opt/alicevision/qml/AliceVision/libqtAliceVisionPlugin.so.0.1
#6  0x00007fff6ac34713 in QtPrivate::QSlotObject<void (qtAliceVision::MViewStats::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
    at /opt/alicevision/qml/AliceVision/libqtAliceVisionPlugin.so.0.1
#7  0x00007ffff60afa97 in  () at /usr/lib64/libQt5Core.so.5
#8  0x00007fff6ac283a9 in qtAliceVision::MViewStats::sfmDataChanged() () at /opt/alicevision/qml/AliceVision/libqtAliceVisionPlugin.so.0.1
#9  0x00007fff6ac5e897 in qtAliceVision::MViewStats::setMSfmData(qtAliceVision::MSfMData*) () at /opt/alicevision/qml/AliceVision/libqtAliceVisionPlugin.so.0.1
#10 0x00007fff6ac27fd2 in qtAliceVision::MViewStats::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) () at /opt/alicevision/qml/AliceVision/libqtAliceVisionPlugin.so.0.1
#11 0x00007ffff5c12381 in  () at /usr/lib64/libQt5Qml.so.5
#12 0x00007ffff5c77e8e in  () at /usr/lib64/libQt5Qml.so.5
#13 0x00007ffff5c81595 in  () at /usr/lib64/libQt5Qml.so.5
#14 0x00007ffff5c82c93 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () at /usr/lib64/libQt5Qml.so.5
#15 0x00007ffff5c5b806 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () at /usr/lib64/libQt5Qml.so.5
#16 0x00007ffff60af5dc in  () at /usr/lib64/libQt5Core.so.5
#17 0x00007fff6ac26693 in qtAliceVision::MSfMData::statusChanged(qtAliceVision::MSfMData::Status) () at /opt/alicevision/qml/AliceVision/libqtAliceVisionPlugin.so.0.1
#18 0x00007fff6ac5b048 in qtAliceVision::MSfMData::setStatus(qtAliceVision::MSfMData::Status) () at /opt/alicevision/qml/AliceVision/libqtAliceVisionPlugin.so.0.1
#19 0x00007fff6ac5ab28 in qtAliceVision::MSfMData::onSfmDataReady(aliceVision::sfmData::SfMData*) () at /opt/alicevision/qml/AliceVision/libqtAliceVisionPlugin.so.0.1
#20 0x00007fff6ac5b639 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<aliceVision::sfmData::SfMData*>, void, void (qtAliceVision::MSfMData::*)(aliceVision::sfmData::SfMData*)>::call(void (qtAliceVision::MSfMData::*)(aliceVision::sfmData::SfMData*), qtAliceVision::MSfMData*, void**) () at /opt/alicevision/qml/AliceVision/libqtAliceVisionPlugin.so.0.1
#21 0x00007fff6ac5b5aa in void QtPrivate::FunctionPointer<void (qtAliceVision::MSfMData::*)(aliceVision::sfmData::SfMData*)>::call<QtPrivate::List<aliceVision::sfmData::SfMData*>, void>(void (qtAliceVision::MSfMData::*)(aliceVision::sfmData::SfMData*), qtAliceVision::MSfMData*, void**) () at /opt/alicevision/qml/AliceVision/libqtAliceVisionPlugin.so.0.1
#22 0x00007fff6ac5b515 in QtPrivate::QSlotObject<void (qtAliceVision::MSfMData::*)(aliceVision::sfmData::SfMData*), QtPrivate::List<aliceVision::sfmData::SfMData*>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    () at /opt/alicevision/qml/AliceVision/libqtAliceVisionPlugin.so.0.1
#23 0x00007ffff60a50aa in QObject::event(QEvent*) () at /usr/lib64/libQt5Core.so.5
#24 0x00007ffff0d11aa5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#25 0x00007ffff607fda8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#26 0x00007ffff60804a0 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib64/libQt5Core.so.5
#27 0x00007ffff60d0290 in  () at /usr/lib64/libQt5Core.so.5
#28 0x00007ffff517b9cb in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#29 0x00007ffff517bc88 in  () at /usr/lib64/libglib-2.0.so.0
#30 0x00007ffff517bd3f in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#31 0x00007ffff60cdb9d in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#32 0x00007ffff607c6b6 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#33 0x00007ffff60809b6 in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#34 0x00007ffff14cd3e0 in  () at /usr/lib/python3.7/site-packages/PySide2/QtWidgets.cpython-37m-x86_64-linux-gnu.so
#35 0x00007ffff7b62fd3 in _PyMethodDef_RawFastCallKeywords () at /usr/lib64/libpython3.7m.so.1.0
#36 0x00007ffff7b62bc3 in  () at /usr/lib64/libpython3.7m.so.1.0
#37 0x00007ffff7b5bc3a in _PyEval_EvalFrameDefault () at /usr/lib64/libpython3.7m.so.1.0
#38 0x00007ffff7b58de5 in _PyEval_EvalCodeWithName () at /usr/lib64/libpython3.7m.so.1.0
#39 0x00007ffff7b58bd3 in PyEval_EvalCode () at /usr/lib64/libpython3.7m.so.1.0
#40 0x00007ffff7b92204 in  () at /usr/lib64/libpython3.7m.so.1.0
#41 0x00007ffff7b62f3f in _PyMethodDef_RawFastCallKeywords () at /usr/lib64/libpython3.7m.so.1.0
#42 0x00007ffff7b62ae8 in  () at /usr/lib64/libpython3.7m.so.1.0
#43 0x00007ffff7b5a8f3 in _PyEval_EvalFrameDefault () at /usr/lib64/libpython3.7m.so.1.0
#44 0x00007ffff7b58de5 in _PyEval_EvalCodeWithName () at /usr/lib64/libpython3.7m.so.1.0
#45 0x00007ffff7b70123 in _PyFunction_FastCallKeywords () at /usr/lib64/libpython3.7m.so.1.0
#46 0x00007ffff7b629af in  () at /usr/lib64/libpython3.7m.so.1.0
#47 0x00007ffff7b5a8f3 in _PyEval_EvalFrameDefault () at /usr/lib64/libpython3.7m.so.1.0
#48 0x00007ffff7b58de5 in _PyEval_EvalCodeWithName () at /usr/lib64/libpython3.7m.so.1.0
#49 0x00007ffff7b786f0 in _PyFunction_FastCallDict () at /usr/lib64/libpython3.7m.so.1.0
```

**Desktop (please complete the following and other pertinent information):**
 - OS: Linux
 - Python version 3.7
 - Qt/PySide version 5.15 (QT) / 5.14 (PySide)
 - Meshroom version: please specify if you are using a release version or your own build
   - Commit reference 883a0d81458c92f919b4017b8f3f10edb9e288c5

**Comment by skinkie** [comment]
There is another issue for this one as well.

**Comment by simogasp** [comment]
is the issue still there in the new version?

**Comment by skinkie** [comment]
> is the issue still there in the new version?

Last time I checked for an update, I could not even get it compiled (QT issues). I'll check today.

**Comment by cbentejac** [comment]
This is fixed in recent versions of Meshroom, closing this issue.
